#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Issue #57: the Host exists and answers on loopback. Droplet, play, /healthz,
# credential inventory. Instance facts stay out of the tree in $HOST_CONF.
HOST_CONF="$HOME/.config/tracewake"
ENV_FILE="$HOST_CONF/host.env"
TFVARS="$HOST_CONF/host.tfvars"
TFSTATE="$HOST_CONF/terraform.tfstate"
TFDATA="$HOST_CONF/tofu-data"
INVENTORY="$HOST_CONF/inventory.yml"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY="$REPO_ROOT/deploy/ansible/host.yml"

mkdir -p "$HOST_CONF" "$TFDATA"
chmod 700 "$HOST_CONF"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

[[ -f "$PLAY" ]] || { warn "run this from the tracewake checkout (no $PLAY)"; exit 1; }

banner "Tracewake Host (#57)"

# ── 1. Tools ──────────────────────────────────────────────────────────────
stage "Tools: tofu, ansible, ssh"
say "The runbook shells out to OpenTofu, Ansible, and OpenSSH."
missing=()
command -v tofu >/dev/null 2>&1 || missing+=("tofu - OpenTofu: https://opentofu.org/docs/intro/install/")
command -v ansible-playbook >/dev/null 2>&1 || missing+=("ansible-playbook - Ansible: https://docs.ansible.com/")
command -v ssh >/dev/null 2>&1 || missing+=("ssh - OpenSSH client")
if (( ${#missing[@]} )); then
  warn "missing tools:"
  for m in "${missing[@]}"; do note "  - $m"; done
  note "Install them, then re-run this wizard."
  exit 1
fi
say "tofu, ansible-playbook, and ssh are all present."

# ── 2. Droplet ────────────────────────────────────────────────────────────
stage "Droplet: token and identifiers"
say "OpenTofu needs a DigitalOcean token plus the five identifiers from #55."
open_url "https://cloud.digitalocean.com/account/api/tokens"
step "API → Tokens → Generate New Token (write scope), then copy it."
ask_secret DIGITALOCEAN_TOKEN "Paste the DigitalOcean token:"
: "${DIGITALOCEAN_TOKEN:?DigitalOcean token is required}"
write_env DIGITALOCEAN_TOKEN "$DIGITALOCEAN_TOKEN"
export DIGITALOCEAN_TOKEN

if [[ -f "$TFVARS" ]] && confirm "Reuse existing $TFVARS"; then
  say "Reusing $TFVARS."
else
  ask TF_NAME "Droplet name [tracewake]:"
  : "${TF_NAME:=tracewake}"
  ask TF_REGION "Region [nyc1]:"
  : "${TF_REGION:=nyc1}"
  ask TF_SIZE "Size [s-4vcpu-8gb]:"
  : "${TF_SIZE:=s-4vcpu-8gb}"
  open_url "https://cloud.digitalocean.com/networking/vpcs"
  step "Networking → VPCs: open your VPC and copy its UUID."
  ask TF_VPC_UUID "Paste the VPC UUID:"
  : "${TF_VPC_UUID:?VPC UUID is required}"
  open_url "https://cloud.digitalocean.com/account/security"
  step "Account → Security → SSH keys: copy the fingerprint of this machine's key."
  ask TF_SSH_KEY "Paste the SSH key fingerprint (or ID):"
  : "${TF_SSH_KEY:?SSH key is required}"
  umask 077
  cat > "$TFVARS" <<EOF
name       = "$TF_NAME"
region     = "$TF_REGION"
size       = "$TF_SIZE"
vpc_uuid   = "$TF_VPC_UUID"
ssh_key    = "$TF_SSH_KEY"
EOF
  say "Wrote $TFVARS."
fi

export TF_DATA_DIR="$TFDATA"
say "Planning deploy/tofu with $TFVARS (state stays in $HOST_CONF)."
(cd "$REPO_ROOT/deploy/tofu" && tofu init -input=false && tofu plan -input=false -state="$TFSTATE" -var-file="$TFVARS" -out="$HOST_CONF/host.plan")
pause "Review the plan above."
if ! confirm "Apply and create the droplet (billable; prevent_destroy is on)"; then
  note "Droplet not created. Re-run to apply $HOST_CONF/host.plan later."
  exit 0
fi
(cd "$REPO_ROOT/deploy/tofu" && tofu apply -input=false -state="$TFSTATE" "$HOST_CONF/host.plan")
HOST_IP=$(cd "$REPO_ROOT/deploy/tofu" && tofu output -raw -state="$TFSTATE" host_ip)
write_env HOST_IP "$HOST_IP"
say "Host IP: $HOST_IP"
note "tofu wrote .terraform.lock.hcl next to the module; leave it untracked or delete it."

# ── 3. Play ───────────────────────────────────────────────────────────────
stage "Play: instance inventory"
say "The play needs the eight installation facts from INSTALL.md, plus the agent."
ask SSH_KEY_FILE "Private key path [~/.ssh/id_ed25519]:"
: "${SSH_KEY_FILE:=~/.ssh/id_ed25519}"
SSH_KEY_FILE="${SSH_KEY_FILE/#\~/$HOME}"
write_env SSH_KEY_FILE "$SSH_KEY_FILE"
if [[ -f "$INVENTORY" ]] && confirm "Reuse existing $INVENTORY"; then
  say "Reusing $INVENTORY."
else
  : "${HOST_IP:?Host IP is missing; stage 2 did not complete}"
  ask INV_HOSTNAME "Dashboard DNS name, no scheme [tracewake.stephens.page]:"
  : "${INV_HOSTNAME:=tracewake.stephens.page}"
  ask INV_REPO "Product repository clone URL:"
  : "${INV_REPO:?Repository URL is required}"
  ask INV_REVISION "Reviewed product revision [main]:"
  : "${INV_REVISION:=main}"
  ask INV_NAME "Commit author name:"
  : "${INV_NAME:?Author name is required}"
  ask INV_EMAIL "Commit author email:"
  : "${INV_EMAIL:?Author email is required}"
  ask INV_KEY_COMMENT "Signing key label [tracewake-host]:"
  : "${INV_KEY_COMMENT:=tracewake-host}"
  ask INV_TARGET "Initial target repository slug [owner/repo]:"
  : "${INV_TARGET:?Target slug is required}"
  ask INV_WORKSPACE "Box checkout path [/home/loop/workspace]:"
  : "${INV_WORKSPACE:=/home/loop/workspace}"
  ask INV_AGENT "Agent [grok]:"
  : "${INV_AGENT:=grok}"
  umask 077
  cat > "$INVENTORY" <<EOF
tracewake:
  hosts:
    tracewake-host:
      ansible_host: "$HOST_IP"
      ansible_user: root
      ansible_ssh_private_key_file: "$SSH_KEY_FILE"
      tracewake_hostname: "$INV_HOSTNAME"
      tracewake_repository: "$INV_REPO"
      tracewake_revision: "$INV_REVISION"
      loop_commit_author_name: "$INV_NAME"
      loop_commit_author_email: "$INV_EMAIL"
      loop_signing_key_comment: "$INV_KEY_COMMENT"
      loop_target_repository: "$INV_TARGET"
      loop_scripts_workspace: "$INV_WORKSPACE"
      loop_agent_name: "$INV_AGENT"
EOF
  say "Wrote $INVENTORY."
fi
say "Check mode first (reports changes; defers operations needing new binaries)."
ansible-playbook -i "$INVENTORY" "$PLAY" --check --diff
pause "Review the check-mode diff above."
ansible-playbook -i "$INVENTORY" "$PLAY"

# ── 4. Health ─────────────────────────────────────────────────────────────
stage "Health: /healthz on loopback"
say "The Dashboard listens on 127.0.0.1:8100; Caddy is the only public origin."
if ssh -i "$SSH_KEY_FILE" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 "root@$HOST_IP" 'curl -sf http://127.0.0.1:8100/healthz'; then
  printf '\n'; say "/healthz answers on loopback."
else
  warn "/healthz did not answer. Check the Dashboard and Caddy units on the Host, then re-run."
  SKIPPED+=("/healthz on loopback (ssh root@$HOST_IP 'curl -sf http://127.0.0.1:8100/healthz')")
fi

# ── 5. Credentials ────────────────────────────────────────────────────────
stage "Credentials: inventory on the Host"
say "Runs the mechanical audit from INSTALL.md step 5 on the Host."
if ssh -i "$SSH_KEY_FILE" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 "root@$HOST_IP" 'cd /srv/tracewake/loop && ./assert-credentials.sh'; then
  say "Inventory exits 0: the Host is dispatch-ready."
else
  warn "Inventory ran with violations. Expected on an empty machine; the #57 box is that it runs."
  step "Work INSTALL.md step 5 on the Host (gh login, target token, subscription, sbx login), then re-run."
  SKIPPED+=("credential violations on the Host (INSTALL.md step 5)")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
