#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Issue #59: the Host can mail, hold a Grok login, and hold both Target tokens.
# Instance facts stay in $HOST_CONF (from host-up) and on the Host. A From
# address, GitHub account, or owner/name slug is required from the operator or
# from that Host config — not defaulted in this file.
HOST_CONF="$HOME/.config/tracewake"
ENV_FILE="$HOST_CONF/host.env"
INVENTORY="$HOST_CONF/inventory.yml"
MAIL_DIR=/etc/tracewake/mail
MAIL_SECRET="$MAIL_DIR/secret"
NOTIFY_CMD="$MAIL_DIR/notify"
INVITE_CMD="$MAIL_DIR/invite"
TOKEN_DIR=/home/loop/.config/loop
GROK_BIN=/home/loop/.grok/bin/grok
GROK_AUTH=/home/loop/.grok/auth.json
GROK_ADAPTER=/home/loop/loop/agents/grok.sh
SIGNING_PUB=/home/loop/.ssh/loop_signing_ed25519.pub
ASSERT=/home/loop/loop/assert-credentials.sh

mkdir -p "$HOST_CONF"
chmod 700 "$HOST_CONF"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

# Inventory values already captured by host-up, if that file is here.
_inv() {
  local key="$1"
  [[ -f "$INVENTORY" ]] || return 0
  python3 -c '
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"^\s*%s:\s*\"?([^\"\n]+?)\"?\s*$" % sys.argv[2], text, re.M)
print(m.group(1).strip() if m else "")
' "$INVENTORY" "$key" 2>/dev/null || true
}

if [[ -z "${HOST_IP:-}" ]]; then
  HOST_IP="$(_existing HOST_IP || true)"
fi
if [[ -z "${HOST_IP:-}" ]]; then
  HOST_IP="$(_inv ansible_host)"
fi
if [[ -z "${SSH_KEY_FILE:-}" ]]; then
  SSH_KEY_FILE="$(_existing SSH_KEY_FILE || true)"
fi
if [[ -n "${SSH_KEY_FILE:-}" ]]; then
  SSH_KEY_FILE="${SSH_KEY_FILE/#\~/$HOME}"
fi
: "${SSH_KEY_FILE:=$HOME/.ssh/id_ed25519}"

on_host() {
  ssh -n -i "$SSH_KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    -o ConnectTimeout=15 "root@${HOST_IP}" "$1"
}
on_host_tty() {
  ssh -t -i "$SSH_KEY_FILE" -o StrictHostKeyChecking=accept-new \
    -o ConnectTimeout=15 "root@${HOST_IP}" "$1"
}
on_host_stdin() {
  ssh -i "$SSH_KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    -o ConnectTimeout=15 "root@${HOST_IP}" "$1"
}
on_loop() {
  on_host "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}
on_loop_stdin() {
  on_host_stdin "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

banner "Host mail, Grok, and Target tokens (#59)"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight: the Host from host-up"
say "This walkthrough SSHes to the Host host-up stood up, as root, then works"
say "as conductor (mail) and loop (Grok, tokens, signing key)."
printf '\n'
if [[ -z "${HOST_IP:-}" ]]; then
  ask HOST_IP "Host IP (host-up writes HOST_IP to $ENV_FILE):"
fi
: "${HOST_IP:?Host IP is required; run wizards/host-up.sh first}"
write_env HOST_IP "$HOST_IP"
write_env SSH_KEY_FILE "$SSH_KEY_FILE"
if [[ ! -f "$SSH_KEY_FILE" ]]; then
  warn "SSH key $SSH_KEY_FILE is missing."
  exit 1
fi
if ! on_host 'true' >/dev/null 2>&1; then
  warn "cannot SSH to root@$HOST_IP with $SSH_KEY_FILE."
  note "Finish wizards/host-up.sh, then re-run this wizard."
  exit 1
fi
printf '  %s✓%s SSH to root@%s\n' "$GREEN" "$RESET" "$HOST_IP"
if ! on_host 'getent passwd conductor >/dev/null && getent passwd loop >/dev/null'; then
  warn "conductor or loop is missing. Re-apply the host play, then re-run."
  exit 1
fi
printf '  %s✓%s conductor and loop accounts exist\n' "$GREEN" "$RESET"
if ! on_host "test -f $SIGNING_PUB"; then
  warn "no signing key at $SIGNING_PUB. Re-apply the host play, then re-run."
  exit 1
fi
printf '  %s✓%s signing key present\n' "$GREEN" "$RESET"
on_host "ssh-keygen -lf $SIGNING_PUB" | sed 's/^/    /'
if ! on_loop "test -x $GROK_BIN"; then
  warn "Grok is not installed for loop. Inventory should set loop_agent_name to grok."
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(on_loop "$GROK_BIN --version" | tr -d '\r')"
INV_EMAIL="$(_inv loop_commit_author_email)"
INV_KEY_COMMENT="$(_inv loop_signing_key_comment)"
printf '\n'
pause "Press Enter to mint the mail secret."

# ── 2. Google app password ────────────────────────────────────────────────
stage "Mail: Google app password"
say "Notify and invite send through Google SMTP as the operator's mailbox."
say "The Host is not a mail server. Google shows the 16-character password once."
printf '\n'
ask MAIL_FROM "From and notify-to address${INV_EMAIL:+ [$INV_EMAIL]}:"
if [[ -z "${MAIL_FROM:-}" && -n "$INV_EMAIL" ]]; then
  MAIL_FROM="$INV_EMAIL"
fi
: "${MAIL_FROM:?From address is required}"
write_env MAIL_FROM "$MAIL_FROM"
if on_host "test -s $MAIL_SECRET" && confirm "Reuse the mail secret already on the Host"; then
  say "Keeping $MAIL_SECRET."
else
  open_url "https://myaccount.google.com/apppasswords"
  step "2-Step Verification must already be on for $MAIL_FROM."
  step "If the page is missing: Security → 2-Step Verification → App passwords."
  step "App name: tracewake-host"
  step "Create, then copy the 16-character password (spaces are optional)."
  printf '\n'
  note "Workspace and Advanced Protection accounts can hide this page. If it"
  note "refuses, enable app passwords for the mailbox or mint a new one."
  printf '\n'
  ask_secret MAIL_APP_PASSWORD "Paste the app password:"
  MAIL_APP_PASSWORD="${MAIL_APP_PASSWORD// /}"
  if [[ -z "${MAIL_APP_PASSWORD:-}" ]]; then
    warn "No app password. Re-run when you have one."
    exit 1
  fi
  if ! printf '%s\n' "$MAIL_APP_PASSWORD" | on_host_stdin "
    umask 077
    mkdir -p /etc/tracewake $MAIL_DIR
    chown conductor:conductor /etc/tracewake
    chmod 0700 /etc/tracewake
    cat > ${MAIL_SECRET}.new
    mv ${MAIL_SECRET}.new $MAIL_SECRET
    chown -R conductor:conductor $MAIL_DIR
    chmod 0700 $MAIL_DIR
    chmod 0600 $MAIL_SECRET
  "; then
    warn "could not write $MAIL_SECRET on the Host."
    unset MAIL_APP_PASSWORD
    exit 1
  fi
  unset MAIL_APP_PASSWORD
  printf '  %s✓%s %s mode 0600, owner conductor\n' "$GREEN" "$RESET" "$MAIL_SECRET"
fi

printf '\n'
pause "Press Enter to install the mail commands and prove isolation."

# ── 3. Shims, isolation, test send ────────────────────────────────────────
stage "Mail: commands, isolation, a real send"
say "Two Host commands implement the product seams: notify is subject + link,"
say "invite names the recipient. Both read the secret; loop cannot."
printf '\n'
if ! on_host_stdin "MAIL_FROM=$(printf '%q' "$MAIL_FROM") python3 -" <<'PY'
import os, pathlib, sys
from_addr = os.environ["MAIL_FROM"]
mail_dir = pathlib.Path("/etc/tracewake/mail")
mail_dir.mkdir(parents=True, exist_ok=True)
secret = mail_dir / "secret"
send = '''#!/usr/bin/env python3
import argparse, sys, smtplib
from email.message import EmailMessage
from pathlib import Path
FROM = %r
SECRET = Path("/etc/tracewake/mail/secret")
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--to", required=True)
    p.add_argument("subject")
    p.add_argument("link", nargs="?", default="")
    args = p.parse_args()
    body = sys.stdin.read()
    if args.link:
        body = body.rstrip() + "\\n\\n" + args.link + "\\n"
    msg = EmailMessage()
    msg["From"], msg["To"], msg["Subject"] = FROM, args.to, args.subject
    msg.set_content(body)
    with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as smtp:
        smtp.starttls()
        smtp.login(FROM, SECRET.read_text().strip())
        smtp.send_message(msg)
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
''' % (from_addr,)
notify = '''#!/bin/bash
exec /etc/tracewake/mail/send --to %r "$@"
''' % (from_addr,)
invite = '''#!/bin/bash
to=${1:?usage: invite <to> <subject> [link]}
shift
exec /etc/tracewake/mail/send --to "$to" "$@"
'''
(mail_dir / "send").write_text(send)
(mail_dir / "notify").write_text(notify)
(mail_dir / "invite").write_text(invite)
import pwd, grp
uid = pwd.getpwnam("conductor").pw_uid
gid = grp.getgrnam("conductor").gr_gid
os.chown(mail_dir, uid, gid)
os.chmod(mail_dir, 0o700)
if secret.exists():
    os.chown(secret, uid, gid)
    os.chmod(secret, 0o600)
for name in ("send", "notify", "invite"):
    path = mail_dir / name
    os.chmod(path, 0o755)
    os.chown(path, uid, gid)
print("installed")
PY
then
  warn "could not install $NOTIFY_CMD and $INVITE_CMD."
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$NOTIFY_CMD"
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$INVITE_CMD"
write_env MAIL_NOTIFY_COMMAND "$NOTIFY_CMD"
write_env MAIL_INVITE_COMMAND "$INVITE_CMD"

say "Isolation: the Run account cannot read the secret, and it is not in loop's home."
if on_loop "test -r $MAIL_SECRET"; then
  warn "loop can read $MAIL_SECRET. Owner/mode are wrong."
  exit 1
fi
printf '  %s✓%s loop cannot read %s\n' "$GREEN" "$RESET" "$MAIL_SECRET"
if on_loop "ls $MAIL_DIR >/dev/null 2>&1"; then
  warn "loop can list $MAIL_DIR; it must be conductor 0700."
  exit 1
fi
printf '  %s✓%s loop cannot list %s\n' "$GREEN" "$RESET" "$MAIL_DIR"
if on_host "find /home/loop -xdev -samefile $MAIL_SECRET 2>/dev/null | grep -q ."; then
  warn "the mail secret is reachable from /home/loop."
  exit 1
fi
printf '  %s✓%s secret is not under /home/loop\n' "$GREEN" "$RESET"
if on_loop 'command -v sbx >/dev/null && sbx secret ls 2>/dev/null' | grep -qiE 'smtp|mail.secret|app.password'; then
  warn "the Execution Boundary's secret store mentions mail."
  exit 1
fi
printf '  %s✓%s no mail secret in sbx secret ls\n' "$GREEN" "$RESET"

say "Sending one notify and one invite to $MAIL_FROM via Google SMTP."
remote_notify=$(printf '%q ' "$NOTIFY_CMD" "Tracewake notify test" "https://example.test/notify")
if ! printf 'Notify command is live on this Host.\n' |
     on_host_stdin "su - conductor -s /bin/bash -c $(printf '%q' "$remote_notify")"; then
  warn "notify send failed. Check the app password and that 2-Step Verification is on."
  exit 1
fi
printf '  %s✓%s notify accepted by Google SMTP\n' "$GREEN" "$RESET"
remote_invite=$(printf '%q ' "$INVITE_CMD" "$MAIL_FROM" "Tracewake invite test" "https://example.test/invite")
if ! printf 'Invite command is live on this Host.\n' |
     on_host_stdin "su - conductor -s /bin/bash -c $(printf '%q' "$remote_invite")"; then
  warn "invite send failed."
  exit 1
fi
printf '  %s✓%s invite accepted by Google SMTP\n' "$GREEN" "$RESET"
printf '\n'
note "Check $MAIL_FROM for those two subjects, From $MAIL_FROM."
if ! confirm "Did both messages arrive from that address"; then
  SKIPPED+=("confirm notify and invite arrived at $MAIL_FROM (SMTP accepted; check spam)")
fi
printf '\n'
pause "Press Enter to log Grok in."

# ── 4. Grok login ─────────────────────────────────────────────────────────
stage "Grok: subscription login, no metered key"
say "The box is headless, so this is a device-code exchange in your browser."
printf '\n'
METERED_SET=""
while IFS= read -r NAME; do
  [[ -n "$NAME" ]] || continue
  if on_loop "test -n \"\${${NAME}:-}\"" 2>/dev/null; then
    METERED_SET="$METERED_SET $NAME"
  fi
done < <(on_loop "$GROK_ADAPTER --metered-env-names" 2>/dev/null || true)
if [[ -n "$METERED_SET" ]]; then
  warn "metered keys are set in loop's environment:$METERED_SET"
  note "Any one of them supersedes the subscription and bills per token."
  exit 1
fi
printf '  %s✓%s no metered xAI key in the Run account environment\n' "$GREEN" "$RESET"
if on_loop 'test -f /home/loop/.grok/config.toml && grep -qE "^[[:space:]]*(api_key|env_key)[[:space:]]*=" /home/loop/.grok/config.toml' 2>/dev/null; then
  warn "/home/loop/.grok/config.toml sets a model api_key or env_key. Remove it."
  exit 1
fi
printf '  %s✓%s no model key in the agent config\n' "$GREEN" "$RESET"
if on_loop "test -f /home/loop/.claude/.credentials.json"; then
  warn "Claude credentials are on this Host. Unattended work here is Grok; leave Claude off this machine."
fi
if on_loop "test -f $GROK_AUTH" && confirm "Grok auth.json already exists; skip login"; then
  say "Keeping the existing Grok session."
else
  step "A URL and code will print on the Host."
  step "Open the URL, enter the code, choose the subscription account — not an API key."
  printf '\n'
  pause "Press Enter to start grok login --device-auth."
  on_host_tty "su - loop -s /bin/bash -c $(printf '%q' "$GROK_BIN login --device-auth")" || true
fi
if ! on_loop "test -f $GROK_AUTH"; then
  warn "no credential at $GROK_AUTH. Re-run this stage."
  exit 1
fi
on_loop "chmod 0600 $GROK_AUTH" || true
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$GROK_AUTH"
say "Asking the agent to answer one word on the Host:"
if on_loop "$GROK_BIN -p 'Reply with the single word: ready' --max-turns 1" 2>&1 |
     sed 's/^/    /' | grep -qi 'ready'; then
  printf '  %s✓%s Grok answered on the Host\n' "$GREEN" "$RESET"
else
  warn "Grok did not answer. Re-run the login."
  exit 1
fi
printf '\n'
pause "Press Enter to register the signing key."

# ── 5. Signing key ────────────────────────────────────────────────────────
stage "GitHub: register the signing key"
say "The play generated this key on the Host. Only you can attach it to the"
say "Operator account as a Signing Key — Authentication Key is the trap."
printf '\n'
PUBKEY="$(on_host "cat $SIGNING_PUB" | tr -d '\r')"
printf '%s%s%s\n' "$DIM" "$PUBKEY" "$RESET"
printf '\n'
SIGNING_TITLE="${INV_KEY_COMMENT:-}"
ask SIGNING_TITLE "Key title on GitHub${SIGNING_TITLE:+ [$SIGNING_TITLE]}:"
if [[ -z "${SIGNING_TITLE:-}" && -n "$INV_KEY_COMMENT" ]]; then
  SIGNING_TITLE="$INV_KEY_COMMENT"
fi
: "${SIGNING_TITLE:?Signing key title is required}"
write_env SIGNING_KEY_TITLE "$SIGNING_TITLE"
INV_GITHUB="$(_inv loop_github_account)"
ask GITHUB_ACCOUNT "Operator GitHub account${INV_GITHUB:+ [$INV_GITHUB]}:"
if [[ -z "${GITHUB_ACCOUNT:-}" && -n "$INV_GITHUB" ]]; then
  GITHUB_ACCOUNT="$INV_GITHUB"
fi
: "${GITHUB_ACCOUNT:?GitHub account is required}"
write_env GITHUB_ACCOUNT "$GITHUB_ACCOUNT"
open_url "https://github.com/settings/ssh/new"
step "If that did not open: GitHub → Settings → SSH and GPG keys → New SSH key."
step "Title: $SIGNING_TITLE"
step "Key type: Signing Key. Not Authentication Key."
step "Key: paste the line above, whole."
step "Add SSH key. 'Key is already in use' on a re-run is a pass."
printf '\n'
pause "Registered? Press Enter to check."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  key_body=$(awk '{print $2}' <<<"$PUBKEY")
  if [[ -n "$key_body" ]] && gh api user/ssh_signing_keys --jq '.[].key' 2>/dev/null | grep -qF "$key_body"; then
    printf '  %s✓%s GitHub lists this public key as a signing key for this login\n' "$GREEN" "$RESET"
  else
    warn "GitHub's signing-key list does not include this key yet."
    note "Confirm Key type was Signing Key, then re-run this stage."
    confirm "Continue without the API seeing the key?" || exit 1
  fi
else
  note "gh is not authenticated on this machine; the Enter above is the registration."
fi
printf '\n'
pause "Press Enter to mint the two Target tokens."

# ── 6. Per-target forge tokens ────────────────────────────────────────────
stage "GitHub: one fine-grained token per Target"
say "Each Target's token is scoped to that repository only. The other Target"
say "is the negative probe. Tokens live under loop, mode 0600."
printf '\n'
INV_TARGET="$(_inv loop_target_repository)"
ask TARGET_A "First Target slug (owner/name)${INV_TARGET:+ [$INV_TARGET]}:"
if [[ -z "${TARGET_A:-}" && -n "$INV_TARGET" ]]; then
  TARGET_A="$INV_TARGET"
fi
: "${TARGET_A:?First Target slug is required}"
ask TARGET_B "Second Target slug (owner/name):"
: "${TARGET_B:?Second Target slug is required}"
if [[ "$TARGET_A" == "$TARGET_B" ]]; then
  warn "the two Targets must be different repositories."
  exit 1
fi
write_env TARGET_A "$TARGET_A"
write_env TARGET_B "$TARGET_B"
TOKEN_A="$TOKEN_DIR/$(basename -- "$TARGET_A").token"
TOKEN_B="$TOKEN_DIR/$(basename -- "$TARGET_B").token"
write_env TARGET_A_TOKEN_FILE "$TOKEN_A"
write_env TARGET_B_TOKEN_FILE "$TOKEN_B"
on_loop "mkdir -p $TOKEN_DIR && chmod 0700 $TOKEN_DIR"

mint_token() {
  local repo="$1" dest="$2" other="$3" token="" code="" write_code=""
  say "Token for $repo, stored at $dest"
  if on_loop "test -s $dest" && confirm "Reuse existing $dest"; then
    say "Keeping $dest."
  else
    open_url "https://github.com/settings/personal-access-tokens/new?name=tracewake-$(basename -- "$repo")&contents=write&pull_requests=write"
    step "Token name: tracewake-$(basename -- "$repo")"
    step "Resource owner: ${repo%%/*}"
    step "Expiration: your call. When it lapses a Run fails at push, loudly."
    step "Repository access: Only select repositories → $repo"
    step "  ONE repository. Not $other."
    step "Permissions → Repository permissions:"
    step "  Contents: Read and write"
    step "  Pull requests: Read and write"
    step "  Issues: No access (ADR 0010 — a Run does not fetch tasks)"
    step "  Metadata: Read-only (GitHub adds this)"
    step "  Nothing else."
    step "Generate token, copy it. GitHub shows it once."
    printf '\n'
    ask_secret GITHUB_TOKEN "Paste the token for $repo:"
    token="$GITHUB_TOKEN"
    unset GITHUB_TOKEN
    if [[ -z "$token" ]]; then
      warn "No token for $repo."
      return 1
    fi
    if [[ "$token" != github_pat_* ]]; then
      warn "That does not look like a fine-grained token (github_pat_...)."
      confirm "Send it anyway?" || return 1
    fi
    if ! printf '%s\n' "$token" | on_loop_stdin "umask 077 && cat > ${dest}.new && mv ${dest}.new $dest"; then
      warn "could not write $dest."
      unset token
      return 1
    fi
    unset token
    printf '  %s✓%s %s mode 0600, owner loop\n' "$GREEN" "$RESET" "$dest"
  fi
  code="$(on_loop "token=\$(cat $dest); curl -sS -o /dev/null -w '%{http_code}' -H \"Authorization: Bearer \$token\" -H 'Accept: application/vnd.github+json' https://api.github.com/repos/$repo" | tr -d '\r')"
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %s reachable (%s)\n' "$GREEN" "$RESET" "$repo" "$code"
  else
    warn "$repo answered $code, not 200. 401 is a bad token; 404 is scope or approval."
    return 1
  fi
  code="$(on_loop "token=\$(cat $dest); curl -sS -o /dev/null -w '%{http_code}' -H \"Authorization: Bearer \$token\" -H 'Accept: application/vnd.github+json' https://api.github.com/repos/$other" | tr -d '\r')"
  if [[ "$code" == "404" ]]; then
    printf '  %s✓%s %s invisible (404) — scope holds\n' "$GREEN" "$RESET" "$other"
  elif [[ "$code" == "200" ]]; then
    note "$other is reachable with GET (public repos always are). Probing write."
    write_code="$(on_loop "token=\$(cat $dest); curl -sS -o /dev/null -w '%{http_code}' -X POST -H \"Authorization: Bearer \$token\" -H 'Accept: application/vnd.github+json' https://api.github.com/repos/$other/git/blobs -d '{\"content\":\"dHJhY2V3YWtlLXByb2Jl\",\"encoding\":\"base64\"}'" | tr -d '\r')"
    if [[ "$write_code" == "201" ]]; then
      warn "$other accepted a blob create ($write_code). This token can write the other Target."
      return 1
    fi
    printf '  %s✓%s %s write refused (%s) — scope holds\n' "$GREEN" "$RESET" "$other" "$write_code"
  else
    printf '  %s✓%s %s not writable (%s)\n' "$GREEN" "$RESET" "$other" "$code"
  fi
  return 0
}

mint_token "$TARGET_A" "$TOKEN_A" "$TARGET_B" || exit 1
printf '\n'
mint_token "$TARGET_B" "$TOKEN_B" "$TARGET_A" || exit 1
printf '\n'
pause "Press Enter for the credential inventory."

# ── 7. Inventory ──────────────────────────────────────────────────────────
stage "Inventory: what the Host holds"
say "Re-check metered keys, then run the box audit as loop with both tokens."
say "The model-credential row still names Claude; a Grok Host may show that row"
say "absent. Mail must not appear. Tokens and the signing key must be held."
printf '\n'
METERED_SET=""
while IFS= read -r NAME; do
  [[ -n "$NAME" ]] || continue
  if on_loop "test -n \"\${${NAME}:-}\"" 2>/dev/null; then
    METERED_SET="$METERED_SET $NAME"
  fi
done < <(on_loop "$GROK_ADAPTER --metered-env-names" 2>/dev/null || true)
if [[ -n "$METERED_SET" ]]; then
  warn "metered keys appeared after login:$METERED_SET"
  exit 1
fi
printf '  %s✓%s still no metered xAI key\n' "$GREEN" "$RESET"
on_loop "$ASSERT --token-file $TOKEN_A --token-file $TOKEN_B" || true
if ! on_loop "test -s $TOKEN_A && test -s $TOKEN_B"; then
  warn "a Target token file is missing."
  exit 1
fi
printf '  %s✓%s both Target token files are present\n' "$GREEN" "$RESET"
printf '\n'
say "Instance files (#60) should point at:"
note "  SELECTOR_NOTIFY_COMMAND=$NOTIFY_CMD"
note "  WINDOW_MAIL_COMMAND=$INVITE_CMD"
note "  $TARGET_A token_file=$TOKEN_A"
note "  $TARGET_B token_file=$TOKEN_B"
note "  LOOP_AGENT_COMMAND=$GROK_ADAPTER"

finish
