#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Issue #114: the local Host exists and answers on the published HTTP port.
# Machine, play, instance files, admin, /healthz. Instance facts stay out of
# the tree in $HOST_CONF. wizards/host-up.sh stays the droplet path.
HOST_CONF="${TRACEWAKE_CONF:-$HOME/.config/tracewake}"
ENV_FILE="$HOST_CONF/local.env"
TFVARS="$HOST_CONF/local.tfvars"
INVENTORY="$HOST_CONF/local-inventory.yml"
WINDOW_ENV="$HOST_CONF/local-window.env"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY="$REPO_ROOT/deploy/ansible/host.yml"
UP="$REPO_ROOT/deploy/tofu/local/up.sh"

mkdir -p "$HOST_CONF"
chmod 700 "$HOST_CONF"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

[[ -f "$PLAY" ]] || { warn "run this from the tracewake checkout (no $PLAY)"; exit 1; }
[[ -f "$UP" ]] || { warn "run this from the tracewake checkout (no $UP)"; exit 1; }

_container_write() {
  local dest="$1" owner="$2"
  local tmp
  tmp=$(mktemp)
  cat > "$tmp"
  docker cp "$tmp" "$CONTAINER:$dest"
  rm -f "$tmp"
  docker exec "$CONTAINER" chown "$owner" "$dest"
  docker exec "$CONTAINER" chmod 600 "$dest"
}

banner "Tracewake local Host (#114)"

# ── 1. Tools ──────────────────────────────────────────────────────────────
stage "Tools: docker, tofu, ansible"
say "The runbook shells out to Docker, OpenTofu, and Ansible."
missing=()
command -v docker >/dev/null 2>&1 || missing+=("docker - Docker Engine / Docker Desktop")
command -v tofu >/dev/null 2>&1 || missing+=("tofu - OpenTofu: https://opentofu.org/docs/intro/install/")
command -v ansible-playbook >/dev/null 2>&1 || missing+=("ansible-playbook - Ansible: https://docs.ansible.com/")
if (( ${#missing[@]} )); then
  warn "missing tools:"
  for m in "${missing[@]}"; do note "  - $m"; done
  note "Install them, then re-run this wizard."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "docker is installed but not running. Start Docker Desktop, then re-run."
  exit 1
fi
if ! ansible-doc -t connection community.docker.docker >/dev/null 2>&1; then
  warn "Ansible cannot find community.docker.docker."
  note "Install it: ansible-galaxy collection install community.docker"
  exit 1
fi
say "docker, tofu, ansible-playbook, and community.docker are all present."

# ── 2. Machine ────────────────────────────────────────────────────────────
stage "Machine: container identifiers"
say "OpenTofu needs the three identifiers from #107. State stays in $HOST_CONF."
if [[ -f "$TFVARS" ]] && confirm "Reuse existing $TFVARS"; then
  say "Reusing $TFVARS."
else
  ask TF_NAME "Container name:"
  : "${TF_NAME:?Container name is required}"
  ask CHECKOUT "Absolute path of this checkout:"
  : "${CHECKOUT:?Checkout path is required}"
  CHECKOUT="${CHECKOUT/#\~/$HOME}"
  ask HTTP_PORT "Host port Caddy is published on:"
  : "${HTTP_PORT:?Host port is required}"
  umask 077
  cat > "$TFVARS" <<EOF
name      = "$TF_NAME"
checkout  = "$CHECKOUT"
http_port = $HTTP_PORT
EOF
  say "Wrote $TFVARS."
  write_env TF_NAME "$TF_NAME"
  write_env CHECKOUT "$CHECKOUT"
  write_env HTTP_PORT "$HTTP_PORT"
fi
if ! confirm "Apply deploy/tofu/local and create (or update) the container"; then
  note "Container not created. Re-run to apply $TFVARS later."
  exit 0
fi
export TRACEWAKE_CONF="$HOST_CONF"
"$UP"
CONTAINER=$(cd "$REPO_ROOT/deploy/tofu/local" && tofu output -raw -state="$HOST_CONF/local.tfstate" container_name)
HTTP_URL=$(cd "$REPO_ROOT/deploy/tofu/local" && tofu output -raw -state="$HOST_CONF/local.tfstate" http_url)
write_env CONTAINER "$CONTAINER"
write_env HTTP_URL "$HTTP_URL"
say "Container: $CONTAINER"
say "URL: $HTTP_URL"

# ── 3. Play ───────────────────────────────────────────────────────────────
stage "Play: instance inventory"
say "The play needs the eight installation facts from INSTALL.md, plus the laptop flags."
if [[ -f "$INVENTORY" ]] && confirm "Reuse existing $INVENTORY"; then
  say "Reusing $INVENTORY."
else
  CONTAINER="${CONTAINER:-$(_existing CONTAINER || true)}"
  : "${CONTAINER:?Container name is missing; stage 2 did not complete}"
  ask INV_REPO "Product repository clone URL:"
  : "${INV_REPO:?Repository URL is required}"
  ask INV_REVISION "Reviewed product revision:"
  : "${INV_REVISION:?Revision is required}"
  ask INV_NAME "Commit author name:"
  : "${INV_NAME:?Author name is required}"
  ask INV_EMAIL "Commit author email:"
  : "${INV_EMAIL:?Author email is required}"
  ask INV_KEY_COMMENT "Signing key label:"
  : "${INV_KEY_COMMENT:?Signing key label is required}"
  ask INV_TARGET "Initial target repository slug:"
  : "${INV_TARGET:?Target slug is required}"
  ask INV_WORKSPACE "Box checkout path:"
  : "${INV_WORKSPACE:?Box checkout path is required}"
  ask INV_AGENT "Agent:"
  : "${INV_AGENT:?Agent is required}"
  umask 077
  cat > "$INVENTORY" <<EOF
tracewake:
  hosts:
    local:
      ansible_connection: community.docker.docker
      ansible_host: "$CONTAINER"
      ansible_python_interpreter: /usr/bin/python3
      loop_agent_name: "$INV_AGENT"
      tracewake_hostname: localhost
      tracewake_tls: false
      tracewake_manage_checkout: false
      tracewake_web_reload: true
      tracewake_repository: "$INV_REPO"
      tracewake_revision: "$INV_REVISION"
      loop_commit_author_name: "$INV_NAME"
      loop_commit_author_email: "$INV_EMAIL"
      loop_signing_key_comment: "$INV_KEY_COMMENT"
      loop_target_repository: "$INV_TARGET"
      loop_scripts_workspace: "$INV_WORKSPACE"
EOF
  say "Wrote $INVENTORY."
fi
say "Check mode first (reports changes; defers operations needing new binaries)."
ansible-playbook -i "$INVENTORY" "$PLAY" --check --diff
pause "Review the check-mode diff above."
set +e
ansible-playbook -i "$INVENTORY" "$PLAY"
play_rc=$?
set -e
if [[ "$play_rc" -ne 0 ]]; then
  warn "Play exited $play_rc. A first apply may stop at sbx sign-in; Caddy should already answer."
  SKIPPED+=("host.yml apply (exit $play_rc); wizards/loop-sbx-login.sh if the Execution Boundary failed")
else
  say "Play applied."
fi

# ── 4. Instance ───────────────────────────────────────────────────────────
stage "Instance: env and targets on the Host"
say "An instance is an env file plus a targets file, written on the container."
CONTAINER="${CONTAINER:-$(_existing CONTAINER || true)}"
: "${CONTAINER:?Container name is missing; stage 2 did not complete}"
HTTP_URL="${HTTP_URL:-$(_existing HTTP_URL || true)}"
: "${HTTP_URL:?HTTP URL is missing; stage 2 did not complete}"
if docker exec "$CONTAINER" test -f /etc/tracewake/tracewake.env \
    && docker exec "$CONTAINER" test -f /etc/tracewake/targets.toml \
    && confirm "Reuse existing /etc/tracewake on $CONTAINER"; then
  say "Reusing /etc/tracewake on the container."
else
  ask SEARCH_OWNER "SELECTOR_SEARCH_OWNER (forge account to search):"
  : "${SEARCH_OWNER:?SELECTOR_SEARCH_OWNER is required}"
  ask PROTECTED_REPO "SELECTOR_PROTECTED_REPO (owner/name):"
  : "${PROTECTED_REPO:?SELECTOR_PROTECTED_REPO is required}"
  ask PROTECTED_REF "SELECTOR_PROTECTED_REF:"
  : "${PROTECTED_REF:?SELECTOR_PROTECTED_REF is required}"
  ask PROTECTED_PATHS "SELECTOR_PROTECTED_PATHS:"
  : "${PROTECTED_PATHS:?SELECTOR_PROTECTED_PATHS is required}"
  ask TARGET_REPO "Target repo slug:"
  : "${TARGET_REPO:?Target repo is required}"
  ask WORK_REPO "Target work_repo path on the Host:"
  : "${WORK_REPO:?work_repo is required}"
  ask BOX_REPO "Target box_repo path on the Host:"
  : "${BOX_REPO:?box_repo is required}"
  ask TOKEN_FILE "Target token_file path on the Host:"
  : "${TOKEN_FILE:?token_file is required}"
  ask LABELER "labeler_allowlist GitHub username:"
  : "${LABELER:?labeler_allowlist is required}"
  ask REVIEW_CAP "review_cap:"
  : "${REVIEW_CAP:?review_cap is required}"
  _container_write /etc/tracewake/tracewake.env conductor:conductor <<EOF
TRACEWAKE_TARGETS_FILE=/etc/tracewake/targets.toml
SELECTOR_JOURNAL_DSN=dbname=selector
SELECTOR_BOX_HOST=local
SELECTOR_BOX_COMMAND=box-sources/local.sh
SELECTOR_BOX_FACTS_COMMAND=box-sources/facts-local.sh
SELECTOR_BOX_PROGRESS_COMMAND=box-sources/progress-local.sh
SELECTOR_BOX_LOOP=/srv/tracewake/loop
SELECTOR_LOOP_URL=$HTTP_URL
SELECTOR_NOTIFY_COMMAND=/bin/true
WINDOW_MAIL_COMMAND=/bin/true
WINDOW_COOKIE_SECURE=0
SELECTOR_PROTECTED_REPO=$PROTECTED_REPO
SELECTOR_PROTECTED_REF=$PROTECTED_REF
SELECTOR_PROTECTED_PATHS=$PROTECTED_PATHS
SELECTOR_SEARCH_OWNER=$SEARCH_OWNER
EOF
  _container_write /etc/tracewake/targets.toml conductor:conductor <<EOF
[[target]]
repo = "$TARGET_REPO"
work_repo = "$WORK_REPO"
box_repo = "$BOX_REPO"
token_file = "$TOKEN_FILE"
guest_template = "loop-base:1"
labeler_allowlist = ["$LABELER"]
review_cap = $REVIEW_CAP
landing = "propose"

[target.labels]
ready = "ready-for-agent"
needs_info = "needs-info"
review = "awaiting-review"
human = "ready-for-human"
EOF
  say "Wrote /etc/tracewake/tracewake.env and targets.toml on $CONTAINER."
  docker exec "$CONTAINER" systemctl restart tracewake-web.service || true
fi

# ── 5. Admin ──────────────────────────────────────────────────────────────
stage "Admin: seed the first window account"
say "There is no registration page. The first admin is seeded on the Journal."
CONTAINER="${CONTAINER:-$(_existing CONTAINER || true)}"
: "${CONTAINER:?Container name is missing; stage 2 did not complete}"
ask ADMIN_EMAIL "Admin email:"
: "${ADMIN_EMAIL:?Admin email is required}"
ask_secret ADMIN_PASSWORD "Admin password:"
: "${ADMIN_PASSWORD:?Admin password is required}"
umask 077
cat > "$WINDOW_ENV" <<EOF
WINDOW_URL=${HTTP_URL:-$(_existing HTTP_URL || true)}
WINDOW_ADMIN_EMAIL=$ADMIN_EMAIL
WINDOW_ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF
chmod 600 "$WINDOW_ENV"
say "Wrote $WINDOW_ENV."
set +e
seed_out=$(docker exec -u conductor -w /srv/tracewake/web \
  -e SELECTOR_JOURNAL_DSN=dbname=selector \
  -e WINDOW_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  "$CONTAINER" /srv/tracewake/web/.venv/bin/python seed-admin.py "$ADMIN_EMAIL" 2>&1)
seed_rc=$?
set -e
if [[ "$seed_rc" -eq 0 ]]; then
  say "Seeded $ADMIN_EMAIL."
elif [[ "$seed_out" == *"already exists"* ]]; then
  say "Account $ADMIN_EMAIL already exists."
else
  warn "Seeding failed (exit $seed_rc). The window may still answer; seed later with web/seed-admin.py."
  note "$seed_out"
  SKIPPED+=("seed-admin.py for $ADMIN_EMAIL")
fi

# ── 6. Health ─────────────────────────────────────────────────────────────
stage "Health: /healthz on the published port"
HTTP_URL="${HTTP_URL:-$(_existing HTTP_URL || true)}"
: "${HTTP_URL:?HTTP URL is missing; stage 2 did not complete}"
say "Waiting for $HTTP_URL/healthz."
ok=0
for _ in 1 2 3 4 5 6 7 8 9 10 11 12; do
  if curl -sf --max-time 5 "$HTTP_URL/healthz" >/dev/null; then
    ok=1
    break
  fi
  sleep 5
done
if [[ "$ok" -eq 1 ]]; then
  say "$HTTP_URL/healthz answers."
  open_url "$HTTP_URL/"
  note "Sign in as the seeded admin. A save under web/ reloads the window."
else
  warn "$HTTP_URL/healthz did not answer. Check caddy and tracewake-web on $CONTAINER."
  SKIPPED+=("/healthz at $HTTP_URL/healthz")
fi

finish
