#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Issue #114: the laptop Host walkthrough. OpenTofu's job stays the
# machine (deploy/tofu/local/up.sh). Ansible's job stays the Host
# (host.yml). This wizard writes instance facts out of the tree and
# runs both. host-up.sh stays the droplet path (ADR 0031).
CONF="${TRACEWAKE_CONF:-$HOME/.config/tracewake}"
ENV_FILE="$CONF/local.env"
TFVARS="$CONF/local.tfvars"
TFSTATE="$CONF/local.tfstate"
TFDATA="$CONF/local-tofu-data"
INVENTORY="$CONF/local-inventory.yml"
ADMIN_PASSWORD_FILE="$CONF/admin-password"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY="$REPO_ROOT/deploy/ansible/host.yml"
MODULE="$REPO_ROOT/deploy/tofu/local"

mkdir -p "$CONF" "$TFDATA"
chmod 700 "$CONF"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

[[ -f "$PLAY" ]] || { warn "run this from the tracewake checkout (no $PLAY)"; exit 1; }

# _wait_for TRIES COMMAND...: retry COMMAND every 10s; true on first success.
_wait_for() {
  local tries="$1"; shift
  local i
  for i in $(seq 1 "$tries"); do
    if "$@" >/dev/null 2>&1; then return 0; fi
    sleep 10
  done
  return 1
}

_tofu_output() {
  local name="$1"
  (cd "$MODULE" && TF_DATA_DIR="$TFDATA" tofu output -raw -state="$TFSTATE" "$name")
}

_container_write() {
  local dest="$1"
  docker exec -i "$CONTAINER" tee "$dest" >/dev/null
}

banner "Tracewake local Host (#114)"

# ── 1. Tools ──────────────────────────────────────────────────────────────
stage "Tools: tofu, ansible, docker"
say "The runbook shells out to OpenTofu, Ansible, and Docker."
missing=()
command -v tofu >/dev/null 2>&1 || missing+=("tofu - OpenTofu: https://opentofu.org/docs/intro/install/")
command -v ansible-playbook >/dev/null 2>&1 || missing+=("ansible-playbook - Ansible: https://docs.ansible.com/")
command -v docker >/dev/null 2>&1 || missing+=("docker - Docker Engine, running")
command -v curl >/dev/null 2>&1 || missing+=("curl")
if (( ${#missing[@]} )); then
  warn "missing tools:"
  for m in "${missing[@]}"; do note "  - $m"; done
  note "Install them, then re-run this wizard."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "docker is installed but not running (or this user cannot talk to it)."
  exit 1
fi
if ! ansible-doc -t connection community.docker.docker >/dev/null 2>&1; then
  say "Ansible needs the community.docker collection for the container connection."
  if confirm "Install community.docker via ansible-galaxy now"; then
    ansible-galaxy collection install community.docker
  else
    note "Install it, then re-run: ansible-galaxy collection install community.docker"
    exit 1
  fi
fi
say "tofu, ansible-playbook, docker, and community.docker.docker are present."

# ── 2. Machine ────────────────────────────────────────────────────────────
stage "Machine: local.tfvars and deploy/tofu/local/up.sh"
say "OpenTofu creates one Ubuntu 24.04 systemd container. State stays in $CONF."
if [[ -f "$TFVARS" ]] && confirm "Reuse existing $TFVARS"; then
  say "Reusing $TFVARS."
else
  ask TF_NAME "Container name [tracewake-local]:"
  : "${TF_NAME:=tracewake-local}"
  ask TF_CHECKOUT "Checkout to bind-mount at /srv/tracewake [$REPO_ROOT]:"
  : "${TF_CHECKOUT:=$REPO_ROOT}"
  TF_CHECKOUT="${TF_CHECKOUT/#\~/$HOME}"
  [[ "$TF_CHECKOUT" = /* ]] || TF_CHECKOUT="$(cd "$TF_CHECKOUT" && pwd)"
  ask TF_HTTP_PORT "Host port for Caddy [8080]:"
  : "${TF_HTTP_PORT:=8080}"
  write_env TF_NAME "$TF_NAME"
  write_env TF_CHECKOUT "$TF_CHECKOUT"
  write_env TF_HTTP_PORT "$TF_HTTP_PORT"
  umask 077
  cat > "$TFVARS" <<EOF
name      = "$TF_NAME"
checkout  = "$TF_CHECKOUT"
http_port = $TF_HTTP_PORT
EOF
  say "Wrote $TFVARS."
fi
say "Applying deploy/tofu/local (named volumes keep the Journal and instance files)."
if ! confirm "Apply and create (or update) the container"; then
  note "Machine not applied. Re-run to apply $TFVARS later."
  exit 0
fi
export TRACEWAKE_CONF="$CONF"
"$REPO_ROOT/deploy/tofu/local/up.sh"
CONTAINER="$(_tofu_output container_name)"
HTTP_URL="$(_tofu_output http_url)"
write_env CONTAINER "$CONTAINER"
write_env HTTP_URL "$HTTP_URL"
say "Container: $CONTAINER"
say "Dashboard URL after the play: $HTTP_URL"

# ── 3. Inventory ──────────────────────────────────────────────────────────
stage "Inventory: local-inventory.yml"
say "The play needs the eight installation facts from INSTALL.md, plus the laptop Host flags."
if [[ -f "$INVENTORY" ]] && confirm "Reuse existing $INVENTORY"; then
  say "Reusing $INVENTORY."
else
  : "${CONTAINER:=$(_existing CONTAINER || true)}"
  : "${CONTAINER:?container name is missing; stage 2 did not complete}"
  ask INV_HOSTNAME "Dashboard name, no scheme [localhost]:"
  : "${INV_HOSTNAME:=localhost}"
  ask INV_REPO "Product repository clone URL:"
  : "${INV_REPO:?Repository URL is required}"
  ask INV_REVISION "Reviewed product revision [main]:"
  : "${INV_REVISION:=main}"
  ask INV_NAME "Commit author name:"
  : "${INV_NAME:?Author name is required}"
  ask INV_EMAIL "Commit author email:"
  : "${INV_EMAIL:?Author email is required}"
  ask INV_KEY_COMMENT "Signing key label [local-host]:"
  : "${INV_KEY_COMMENT:=local-host}"
  ask INV_TARGET "Initial target repository slug:"
  : "${INV_TARGET:?Target slug is required}"
  ask INV_WORKSPACE "Box checkout path [/home/loop/workspace]:"
  : "${INV_WORKSPACE:=/home/loop/workspace}"
  ask INV_AGENT "Agent [grok]:"
  : "${INV_AGENT:=grok}"
  write_env INV_HOSTNAME "$INV_HOSTNAME"
  write_env INV_REPO "$INV_REPO"
  write_env INV_REVISION "$INV_REVISION"
  write_env INV_NAME "$INV_NAME"
  write_env INV_EMAIL "$INV_EMAIL"
  write_env INV_TARGET "$INV_TARGET"
  write_env INV_WORKSPACE "$INV_WORKSPACE"
  write_env INV_AGENT "$INV_AGENT"
  umask 077
  cat > "$INVENTORY" <<EOF
tracewake:
  hosts:
    local:
      ansible_connection: community.docker.docker
      ansible_host: "$CONTAINER"
      ansible_python_interpreter: /usr/bin/python3
      tracewake_hostname: "$INV_HOSTNAME"
      tracewake_tls: false
      tracewake_manage_checkout: false
      tracewake_web_reload: true
      tracewake_repository: "$INV_REPO"
      tracewake_revision: "$INV_REVISION"
      loop_commit_author_name: "$INV_NAME"
      loop_commit_author_email: "$INV_EMAIL"
      loop_signing_key_comment: "$INV_KEY_COMMENT"
      loop_target_repository: "$INV_TARGET"
      loop_scripts_workspace: "$INV_WORKSPACE"
      loop_agent_name: "$INV_AGENT"
EOF
  say "Wrote $INVENTORY."
fi

# ── 4. Play ───────────────────────────────────────────────────────────────
stage "Play: ansible-playbook host.yml"
say "Check mode first (reports changes; defers operations needing new binaries)."
ansible-playbook -i "$INVENTORY" "$PLAY" --check --diff
pause "Review the check-mode diff above."
if ansible-playbook -i "$INVENTORY" "$PLAY"; then
  say "host.yml finished."
else
  warn "The play did not finish. A first apply often stops at sbx sign-in."
  note "Caddy is installed before that role; /healthz may already answer."
  note "Runs stay out of reach until wizards/loop-sbx-login.sh and /dev/kvm."
  if ! confirm "Continue with instance files, admin, and /healthz"; then
    exit 1
  fi
  SKIPPED+=("host.yml finished with errors (often sbx sign-in)")
fi

: "${CONTAINER:=$(_existing CONTAINER || true)}"
: "${CONTAINER:?container name is missing; stage 2 did not complete}"
: "${HTTP_URL:=$(_existing HTTP_URL || true)}"
if [[ -z "$HTTP_URL" && -f "$TFSTATE" ]]; then
  HTTP_URL="$(_tofu_output http_url)"
fi

# ── 5. Instance files ─────────────────────────────────────────────────────
stage "Instance: tracewake.env and targets.toml on the container"
say "These files live at /etc/tracewake on the Host, on a named volume."
say "WINDOW_COOKIE_SECURE=0 is set so a plain-HTTP dashboard can sign in."
if docker exec "$CONTAINER" test -f /etc/tracewake/tracewake.env \
    && confirm "Reuse existing instance files on the container"; then
  say "Reusing /etc/tracewake/tracewake.env and targets.toml."
else
  : "${INV_TARGET:=$(_existing INV_TARGET || true)}"
  : "${INV_WORKSPACE:=$(_existing INV_WORKSPACE || true)}"
  ask INV_TARGET "Target repository slug:"
  : "${INV_TARGET:?Target slug is required}"
  ask INV_WORKSPACE "Box checkout path [/home/loop/workspace]:"
  : "${INV_WORKSPACE:=/home/loop/workspace}"
  ask WORK_REPO "Work checkout path [$INV_WORKSPACE]:"
  : "${WORK_REPO:=$INV_WORKSPACE}"
  ask TOKEN_FILE "Per-target token path [/etc/tracewake/tokens/target.token]:"
  : "${TOKEN_FILE:=/etc/tracewake/tokens/target.token}"
  ask LABELER "GitHub username for the labeler allowlist:"
  : "${LABELER:?labeler allowlist needs a GitHub username}"
  ask SEARCH_OWNER "SELECTOR_SEARCH_OWNER (forge owner to search):"
  : "${SEARCH_OWNER:?SELECTOR_SEARCH_OWNER is required}"
  ask PROTECTED_REPO "SELECTOR_PROTECTED_REPO (guardrail tree slug):"
  : "${PROTECTED_REPO:?SELECTOR_PROTECTED_REPO is required}"
  ask PROTECTED_REF "SELECTOR_PROTECTED_REF [refs/heads/main]:"
  : "${PROTECTED_REF:=refs/heads/main}"
  write_env INV_TARGET "$INV_TARGET"
  write_env INV_WORKSPACE "$INV_WORKSPACE"
  write_env SEARCH_OWNER "$SEARCH_OWNER"
  write_env PROTECTED_REPO "$PROTECTED_REPO"
  docker exec "$CONTAINER" mkdir -p /etc/tracewake
  docker exec "$CONTAINER" chown conductor:conductor /etc/tracewake
  docker exec "$CONTAINER" chmod 700 /etc/tracewake
  umask 077
  _container_write /etc/tracewake/tracewake.env <<EOF
# Read by systemd EnvironmentFile= and by an exported shell environment.
TRACEWAKE_TARGETS_FILE=/etc/tracewake/targets.toml
SELECTOR_JOURNAL_DSN=dbname=selector
SELECTOR_BOX_HOST=local
SELECTOR_BOX_COMMAND=box-sources/local.sh
SELECTOR_BOX_FACTS_COMMAND=box-sources/facts-local.sh
SELECTOR_BOX_PROGRESS_COMMAND=box-sources/progress-local.sh
SELECTOR_BOX_MICROVMS_COMMAND=box-sources/microvms-local.sh
SELECTOR_BOX_LOOP=/srv/tracewake/loop
SELECTOR_LOOP_URL=$HTTP_URL
SELECTOR_NOTIFY_COMMAND=/bin/true
WINDOW_MAIL_COMMAND=/bin/true
SELECTOR_PROTECTED_REPO=$PROTECTED_REPO
SELECTOR_PROTECTED_REF=$PROTECTED_REF
SELECTOR_PROTECTED_PATHS=guardrail-sources/paths.txt
SELECTOR_SEARCH_OWNER=$SEARCH_OWNER
WINDOW_COOKIE_SECURE=0
EOF
  _container_write /etc/tracewake/targets.toml <<EOF
[[target]]
repo = "$INV_TARGET"
work_repo = "$WORK_REPO"
box_repo = "$INV_WORKSPACE"
token_file = "$TOKEN_FILE"
guest_template = "loop-base:1"
labeler_allowlist = ["$LABELER"]
review_cap = 20
landing = "propose"

[target.labels]
ready = "ready-for-agent"
needs_info = "needs-info"
review = "awaiting-review"
human = "ready-for-human"
EOF
  docker exec "$CONTAINER" chown conductor:conductor \
    /etc/tracewake/tracewake.env /etc/tracewake/targets.toml
  docker exec "$CONTAINER" chmod 600 \
    /etc/tracewake/tracewake.env /etc/tracewake/targets.toml
  say "Wrote instance files on $CONTAINER."
fi
if docker exec "$CONTAINER" systemctl restart tracewake-web.service; then
  say "Restarted the dashboard so WINDOW_COOKIE_SECURE=0 is live."
else
  warn "Could not restart tracewake-web.service; /healthz may still fail until the unit is up."
  SKIPPED+=("restart tracewake-web.service on $CONTAINER")
fi

# ── 6. Admin ──────────────────────────────────────────────────────────────
stage "Admin: seed-admin.py"
say "There is no registration page. Seed the first dashboard admin."
ask ADMIN_EMAIL "Admin email:"
: "${ADMIN_EMAIL:?admin email is required}"
if [[ -f "$ADMIN_PASSWORD_FILE" ]] && confirm "Reuse existing $ADMIN_PASSWORD_FILE"; then
  ADMIN_PASSWORD="$(cat "$ADMIN_PASSWORD_FILE")"
else
  ask_secret ADMIN_PASSWORD "Admin password:"
  : "${ADMIN_PASSWORD:?admin password is required}"
  umask 077
  printf '%s\n' "$ADMIN_PASSWORD" > "$ADMIN_PASSWORD_FILE"
  chmod 600 "$ADMIN_PASSWORD_FILE"
  say "Wrote $ADMIN_PASSWORD_FILE."
fi
write_env ADMIN_EMAIL "$ADMIN_EMAIL"
set +e
seed_out=$(docker exec -u conductor \
    -e WINDOW_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
    "$CONTAINER" \
    bash -lc "cd /srv/tracewake/web && set -a && . /etc/tracewake/tracewake.env && set +a && .venv/bin/python seed-admin.py $(printf '%q' "$ADMIN_EMAIL")" 2>&1)
seed_rc=$?
set -e
if [[ "$seed_rc" -eq 0 ]]; then
  say "Seeded $ADMIN_EMAIL via web/seed-admin.py."
elif [[ "$seed_out" == *"already exists"* ]]; then
  say "Account $ADMIN_EMAIL already exists."
else
  warn "seed-admin.py did not create the account (exit $seed_rc)."
  note "$seed_out"
  SKIPPED+=("seed-admin.py for $ADMIN_EMAIL (re-run or sign in if it already exists)")
fi

# ── 7. Health ─────────────────────────────────────────────────────────────
stage "Health: /healthz on the published port"
: "${HTTP_URL:=$(_existing HTTP_URL || true)}"
: "${HTTP_URL:?http_url is missing; stage 2 did not complete}"
say "The health check is curl http://127.0.0.1:<http_port>/healthz."
say "Waiting on curl $HTTP_URL/healthz (up to five minutes)."
if _wait_for 30 curl -sf --max-time 10 "$HTTP_URL/healthz"; then
  say "$HTTP_URL/healthz answers."
  open_url "$HTTP_URL/"
  step "Sign in as the seeded admin; you should land on the Queue Board at /."
else
  warn "$HTTP_URL/healthz did not answer. Check Caddy and tracewake-web on the container, then re-run."
  SKIPPED+=("curl $HTTP_URL/healthz")
fi
note "The cycle timer stays disabled until credentials exist."
# ──────────────────────────────────────────────────────────────────────────

finish
