#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Log the Loop's SECOND agent in, and prove the credential works inside the
# boundary. The Claude Code counterpart is loop-claude-login.sh; this is #84's,
# and the differences between the two are the ticket.
#
# Grok Build's subscription login is a browser step like the other one, but the
# box is headless and this vendor has a flag for exactly that: `grok login
# --device-auth` prints a URL and a code, you approve them on your own machine,
# and the CLI finishes on the box. So unlike stage 2 of the Claude wizard, this
# one is a device-code exchange rather than a full-screen interface - which is
# also why it can be read back from a plain pipe.
#
# What is left behind is ~loop/.grok/auth.json: an OAuth session with a REFRESH
# TOKEN in it, which is the second difference and the more important one.
#
#   - The credential expires on its own, six hours after it is minted, and
#     refreshes against `auth.x.ai`. That host is on the boundary's egress
#     allowlist for this agent because a Run longer than the token's remaining
#     life needs the refresh mid-Iteration, not only at login.
#   - The credential goes INSIDE the microVM, where the agent can read it, and
#     `sbx`'s host-proxy credential injection does NOT apply. That property held
#     for the first Run under Claude Code and does not hold here; ADR 0012 is
#     where which-property-holds-for-which-agent is written down so that nobody
#     inherits this one wrongly.
#
# The metered-key collision has more doors under this vendor than under the
# other, and all of them are checked below before the login rather than after
# it. The vendor's own README says "The API key takes precedence over browser
# credentials", so logging in on a box that holds one produces a credential that
# is never used and a bill nobody expected.
#
# Run it from the orchestration VM as `conductor`, whose SSH key is the one
# attached to the droplet (`tofu/hosts/loop.tf`):
#
#   sudo -u conductor -i
#   cd /srv/orchestration/lab/single-user-factory/wizards && ./loop-grok-login.sh
#
# Re-runnable: logging in again over an existing session is harmless, and every
# check outside stage 2 is a read.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

LOOP_HOST="${LOOP_HOST:-loop.etadventures.com}"
CREDENTIALS_PATH="/home/loop/.grok/auth.json"
GROK_BIN="/home/loop/.grok/bin/grok"
ADAPTER="/home/loop/loop/agents/grok.sh"

# Nothing this wizard captures is persisted - the credential is established on
# the box and never travels through here.
ENV_FILE=/dev/null

on_loop() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

# The same, with a terminal. The device-code exchange prints a URL and then
# blocks until you approve it, so it needs to stay attached rather than be read
# once and closed.
on_loop_tty() {
  ssh -t -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

banner "The Loop's second agent - log Grok Build in"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight - the box, the agent, the boundary"
say "Nothing here needs you yet. Checking what ansible already left on the box."
printf '\n'

if ! on_loop 'true' >/dev/null 2>&1; then
  warn "cannot reach loop as root@${LOOP_HOST} over SSH."
  note "The droplet's key is conductor's on the orchestration VM. If you are"
  note "someone else, re-run this as: sudo -u conductor -i"
  exit 1
fi
printf '  %s✓%s SSH to root@%s\n' "$GREEN" "$RESET" "$LOOP_HOST"

GROK_VERSION=$(on_loop "${GROK_BIN} --version" 2>/dev/null || true)
if [[ -z "$GROK_VERSION" ]]; then
  warn "Grok Build is not installed, or not runnable as the loop account."
  note "Install it first, which is the same one line that swaps the agent:"
  note "  cd /srv/orchestration/ansible && ansible-playbook loop.yml -e loop_agent_name=grok"
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$GROK_VERSION"

# The pin, checked rather than assumed. The host's copy exists only for the
# login, but a host on one version and a guest on another is a login made
# against a client the Run never uses.
PINNED=$(on_loop "${ADAPTER} --pinned-version" 2>/dev/null || true)
if [[ -n "$PINNED" && "$GROK_VERSION" != *"$PINNED"* ]]; then
  warn "the box is holding ${GROK_VERSION}, and the adapter pins ${PINNED}."
  note "Re-apply the play; it installs the version the adapter asks for."
  exit 1
fi
[[ -n "$PINNED" ]] && printf '  %s✓%s the host matches the adapter'"'"'s pin (%s)\n' \
  "$GREEN" "$RESET" "$PINNED"

# The collision spec #73 story 32 wants made impossible, checked before the
# login rather than after it - and every door rather than the documented one.
# The names are read off the adapter, which is where ADR 0004 puts vendor
# knowledge; restating them here would be a second list to keep in step.
METERED_SET=""
while IFS= read -r NAME; do
  [[ -n "$NAME" ]] || continue
  if on_loop "test -n \"\${${NAME}:-}\"" 2>/dev/null; then
    METERED_SET="${METERED_SET} ${NAME}"
  fi
done < <(on_loop "${ADAPTER} --metered-env-names" 2>/dev/null || true)

if [[ -n "$METERED_SET" ]]; then
  warn "these are set in the loop account's environment:${METERED_SET}"
  note "Any one of them supersedes the login you are about to make and moves"
  note "every Iteration onto metered billing, with no error. The vendor's own"
  note "README says so: \"The API key takes precedence over browser credentials.\""
  note "Find them and remove them first:"
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"grep -rl XAI_API_KEY ~/.bashrc ~/.profile /etc/environment\"'"
  exit 1
fi
printf '  %s✓%s no metered model key in the Run account'"'"'s environment\n' "$GREEN" "$RESET"

if on_loop 'sbx daemon status' >/dev/null 2>&1; then
  printf '  %s✓%s the Execution Boundary is up\n' "$GREEN" "$RESET"
else
  warn "sandboxd is not running - stage 4 cannot prove anything without it."
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx daemon status; sbx diagnose\"'"
  exit 1
fi

# The install host, which the other agent does not need. Grok has no `sbx`
# template, so every Iteration installs the agent inside its own microVM - and
# an allowlist missing x.ai fails at Iteration 1 of an unattended Run rather
# than here.
if on_loop 'sbx policy ls --json' 2>/dev/null | grep -q 'x\.ai:443'; then
  printf '  %s✓%s the boundary allows this agent'"'"'s hosts\n' "$GREEN" "$RESET"
else
  warn "the boundary's egress does not allow x.ai:443."
  note "This agent is installed INSIDE the boundary each Iteration, so without"
  note "it every Iteration fails at the install. The fix is the same one line:"
  note "  cd /srv/orchestration/ansible && ansible-playbook loop.yml -e loop_agent_name=grok"
  exit 1
fi

if on_loop "test -f ${CREDENTIALS_PATH}"; then
  printf '\n'
  note "A model credential is already on the box. Logging in again replaces it,"
  note "which is harmless; stages 3 to 5 re-check it either way."
fi

printf '\n'
pause "Press Enter to log in."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The box - log in as yourself"
say "This is the step only you can take. The box is headless, so this is a"
say "device-code exchange: it prints a URL and a code below, you approve them"
say "in your own browser, and the CLI finishes on the box."
printf '\n'
step "Wait for the URL and the code to appear."
step "Open the URL on your own machine and enter the code."
step "Choose your subscription account, not an API key."
step "Come back here; it completes on its own."
printf '\n'
warn "You are on loop.etadventures.com, not this VM. Nothing else lives there,"
warn "but it is the box an unattended agent runs on - do not ask it to do work."
printf '\n'
pause "Press Enter to start the exchange."

on_loop_tty "${GROK_BIN} login --device-auth" || true

printf '\n'

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The credential - on the box, and only readable by the box"
say "Checking what the login actually left behind, rather than trusting that it"
say "finished."
printf '\n'

if ! on_loop "test -f ${CREDENTIALS_PATH}"; then
  warn "no credential at ${CREDENTIALS_PATH}."
  note "The login did not complete. Re-run this wizard; stage 2 is repeatable."
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$CREDENTIALS_PATH"

CRED_MODE=$(on_loop "stat -c %a ${CREDENTIALS_PATH}" 2>/dev/null || printf '?')
if [[ "$CRED_MODE" == "600" ]]; then
  printf '  %s✓%s mode 0600 - readable by loop and nobody else\n' "$GREEN" "$RESET"
else
  warn "mode is ${CRED_MODE}, not 600. Tightening it."
  on_loop "chmod 0600 ${CREDENTIALS_PATH}" || warn "could not chmod it - do it by hand."
fi

# The expiry, printed rather than assumed. This credential is not the other
# agent's: it dies six hours after it is minted and refreshes against auth.x.ai,
# which is why that host is on the allowlist and why a Run left for an hour is
# a different proposition from one left overnight.
EXPIRES=$(on_loop "jq -r '.[].expires_at // empty' ${CREDENTIALS_PATH} | head -n1" 2>/dev/null || true)
if [[ -n "$EXPIRES" ]]; then
  printf '  %s✓%s the session expires %s, and refreshes against auth.x.ai\n' \
    "$GREEN" "$RESET" "$EXPIRES"
else
  note "could not read an expiry out of the credential - not fatal, but the"
  note "session is time-limited and the refresh host has to stay allowed."
fi

# The file door, checked on the box for the same reason the environment is: a
# per-model api_key in the config resolves AHEAD of the session you just made,
# and that file is copied into every microVM.
if on_loop "test -f /home/loop/.grok/config.toml && grep -qE '^[[:space:]]*(api_key|env_key)[[:space:]]*=' /home/loop/.grok/config.toml" 2>/dev/null; then
  warn "/home/loop/.grok/config.toml sets a model api_key or env_key."
  note "It resolves ahead of the session token and would move billing. The"
  note "adapter refuses to run an Iteration while it is there - remove it."
  SKIPPED+=("remove the model api_key from /home/loop/.grok/config.toml")
else
  printf '  %s✓%s no model key in the agent'"'"'s config\n' "$GREEN" "$RESET"
fi

say "Asking the agent to answer one question, on the box, to prove the session"
say "is live rather than merely present:"
printf '\n'
if on_loop "${GROK_BIN} -p 'Reply with the single word: ready' --max-turns 1" 2>&1 |
     sed 's/^/    /' | grep -qi 'ready'; then
  printf '\n  %s✓%s the agent answered\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "the agent did not answer. The credential is there and the session may"
  warn "not be. Re-run stage 2."
  exit 1
fi

printf '\n'
pause "Press Enter to prove it works inside the boundary."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The boundary - the same credential, inside a microVM"
say "The stage above proved the login works on the host. A Run never runs the"
say "agent there: every Iteration is a fresh microVM which installs the agent"
say "at the pin, gets a copy of the credential, and dies with both. That is a"
say "different claim, so it is proved separately - through the exact adapter a"
say "Run uses."
note "First run pulls the shell sandbox image; give it a couple of minutes."
printf '\n'

PROOF_PROMPT="/tmp/loop-grok-login-proof-$$"
if on_loop "mkdir -p /home/loop/proof && printf 'Reply with the single word: ready\n' > ${PROOF_PROMPT} && cd /home/loop/proof && ${ADAPTER} ${PROOF_PROMPT} 1; rm -f ${PROOF_PROMPT}" 2>&1 |
     sed 's/^/    /' | grep -qi 'ready'; then
  printf '\n  %s✓%s the agent answered from inside a microVM\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "the agent did not answer from inside the boundary."
  note "The credential is fine on the host, so this is the boundary, the install"
  note "or the adapter. Read it on the box:"
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx diagnose; sbx policy ls --wide; sbx policy log --json | tail\"'"
  note "If it is egress, the fix is a line in loop_execution_boundary_egress_by_agent"
  note "saying what breaks without it - not widening the profile."
  SKIPPED+=("prove the credential works inside the boundary")
fi

on_loop 'rm -rf /home/loop/proof' || true

printf '\n'
pause "Press Enter for the credential inventory."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The inventory - what the box holds, and what it may not"
say "Every isolation argument in spec #73 rests on one sentence about what this"
say "box holds. This is that sentence, asserted - and it now grades the second"
say "vendor's keys too, because the adapters are where the names live."
printf '\n'

if on_loop '/home/loop/loop/assert-credentials.sh' 2>&1 | sed 's/^/    /'; then
  printf '\n  %s✓%s the box holds what it is allowed to hold, and nothing it is not\n' \
    "$GREEN" "$RESET"
else
  printf '\n'
  warn "the inventory is not clean. Every violation is named above."
  note "It never fixes what it finds: what to do about a credential that reached"
  note "this box is not a decision to take unattended."
  SKIPPED+=("clear the credential violations named above")
fi

printf '\n'
say "The box is ready for a Run under this agent. Two things point at it:"
printf '\n'
note "  LOOP_AGENT_COMMAND=/home/loop/loop/agents/grok.sh   the Loop's half"
note "  ansible-playbook loop.yml -e loop_agent_name=grok   the box's half"
printf '\n'
say "Which properties hold for which agent is ADR 0012. Read it before quoting"
say "the first Run's guarantees at this one."

finish
