#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Sign the Loop's Execution Boundary in, on a box with no browser.
#
# `sbx` (Docker Sandboxes) is installed and pinned by ansible - `loop.yml`, role
# `loop_execution_boundary` - but it refuses every command that touches a
# sandbox until it holds a Docker identity, and the sign-in it documents opens a
# browser. The box is headless, so that step cannot happen there.
#
# This wizard takes the other route `sbx login` supports: you create a Docker
# personal access token in a browser on your own machine, paste it here once,
# and it goes over SSH into `sbx login --password-stdin` on the box. Nothing is
# written to disk on this side - not the token, not the username - and the
# token is revocable on its own from the same page that issued it.
#
# Run it from the orchestration VM as `conductor`, whose SSH key is the one
# attached to the droplet (`tofu/hosts/loop.tf`):
#
#   sudo -u conductor -i
#   cd /srv/orchestration/lab/single-user-factory/wizards && ./loop-sbx-login.sh
#
# Re-runnable: signing in again over an existing session is harmless, and every
# check below is a read.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Required, and deliberately without a default (issue #3): the box's hostname
# is a fact about an instance, and a wizard that defaulted to somebody else's
# would walk an operator through minting a credential and then place it there.
LOOP_HOST="${LOOP_HOST:-}"
[[ -n ${LOOP_HOST} ]] || {
    printf 'LOOP_HOST is not set, and there is no default for it: where the box of this instance is, is a fact about this instance, not about Tracewake.\n' >&2
    exit 1
}

# Nothing this wizard captures is persisted, so there is no .env to upsert into
# and `ask`'s "[Enter keeps current]" affordance has nothing to offer. Pointed
# at /dev/null deliberately rather than left at the library default, so a stray
# `write_env` cannot drop a Docker token into whatever directory this was run
# from.
ENV_FILE=/dev/null

# Every sbx command runs on the box, as `loop` - the unprivileged account a Run
# executes as, and therefore the account whose sign-in state is the one that
# matters. Signing in as root would leave `loop` still signed out.
on_loop() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

# Same shape, for the one command that has to be fed on stdin. Separate rather
# than a flag on on_loop because ssh's stdin is the difference, and a helper
# that sometimes consumes the caller's stdin is a trap.
on_loop_stdin() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

banner "The Loop's Execution Boundary - sign in"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight - the box, the boundary, the hypervisor"
say "Nothing here needs you yet. Checking what ansible already left on the box."
printf '\n'

if ! on_loop 'true' >/dev/null 2>&1; then
  warn "cannot reach loop as root@${LOOP_HOST} over SSH."
  note "The droplet's key is conductor's on the orchestration VM. If you are"
  note "someone else, re-run this as: sudo -u conductor -i"
  exit 1
fi
printf '  %s✓%s SSH to root@%s\n' "$GREEN" "$RESET" "$LOOP_HOST"

SBX_VERSION=$(on_loop 'sbx version' 2>/dev/null || true)
if [[ -z "$SBX_VERSION" ]]; then
  warn "sbx is not installed, or not runnable as the loop account."
  note "Install it first:  cd /srv/orchestration/ansible && ansible-playbook loop.yml"
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$SBX_VERSION"

# The one prerequisite that is not a package. Without /dev/kvm readable by
# `loop`, sbx will sign in happily and then fail to boot a single microVM.
if on_loop 'test -r /dev/kvm && test -w /dev/kvm'; then
  printf '  %s✓%s /dev/kvm is readable and writable as loop\n' "$GREEN" "$RESET"
else
  warn "loop cannot open /dev/kvm - the boundary cannot start a microVM."
  note "Expected: loop in the kvm group. Re-run ansible-playbook loop.yml."
  exit 1
fi

# sandboxd is a per-user daemon under ~loop/.local/state. Since #99 it is also a
# systemd USER unit (sandboxd.service, with lingering), so on a box the ansible
# play has touched it is already running by the time this wizard gets here and
# this block does nothing. It stays for the box where the play has not run yet.
#
# The unit is tried first because a --detach daemon is one systemd does not own,
# and it leaves the unit a no-op until the next reboot (`sbx daemon start` exits
# 0 on an already-running socket). The --detach fallback is still there on
# purpose: on a box with no unit it is the only way to get a boundary, and the
# wizard's job is to finish the sign-in. Running the play afterwards, or
# rebooting, puts the daemon back under the unit.
if on_loop 'sbx daemon status' >/dev/null 2>&1; then
  printf '  %s✓%s sandboxd is running\n' "$GREEN" "$RESET"
else
  say "sandboxd is not running; starting it."
  # `su -` gives no login session, so neither variable systemctl --user needs is
  # set and it fails with `Failed to connect to bus: No medium found`. Set both.
  on_loop 'export XDG_RUNTIME_DIR=/run/user/$(id -u); export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus; systemctl --user start sandboxd.service' >/dev/null 2>&1 \
    || on_loop 'sbx daemon start --detach' >/dev/null 2>&1 || true
  if on_loop 'sbx daemon status' >/dev/null 2>&1; then
    printf '  %s✓%s sandboxd started\n' "$GREEN" "$RESET"
  else
    warn "sandboxd would not start. Read it on the box:"
    note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx daemon status; sbx diagnose\"'"
    exit 1
  fi
fi

printf '\n'
pause "Press Enter to go and make the token."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Docker - create a personal access token"
say "This is the one step only you can take: it happens in a browser, signed in"
say "as you. The token is what stands in for that browser on a headless box."
printf '\n'
open_url "https://app.docker.com/settings/personal-access-tokens"
step "If that did not open: app.docker.com → your avatar → Account settings →"
step "  Personal access tokens."
step "Select 'Generate new token'."
step "Description: ${LOOP_HOST} - sbx"
step "Expiration: your call. A short one means re-running this wizard, which is"
step "  cheap; the boundary stops working when it lapses, loudly."
step "Access permissions: 'Read-only' is enough - sbx pulls images and proves an"
step "  identity, it does not push. Stage 3 fails loudly if that turns out wrong."
step "Generate, then copy the token. Docker shows it exactly once."
printf '\n'
ask DOCKER_USERNAME "Your Docker username (not your email):"
ask_secret DOCKER_PAT "Paste the token:"

if [[ -z "$DOCKER_USERNAME" || -z "$DOCKER_PAT" ]]; then
  warn "Both a username and a token are needed. Re-run when you have them."
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The box - sign in"
say "Sending the token over SSH into sbx's stdin. It is not echoed, not logged,"
say "and not written to any file on this machine."
printf '\n'

# --password-stdin, never on the command line: an argument would be visible in
# `ps` on the box for the life of the call. The same reason CLAUDE.md gives for
# MYSQL_PWD over `mysql -p<pass>`.
if printf '%s' "$DOCKER_PAT" |
     on_loop_stdin "sbx login --username ${DOCKER_USERNAME} --password-stdin"
then
  printf '  %s✓%s signed in as %s\n' "$GREEN" "$RESET" "$DOCKER_USERNAME"
else
  printf '\n'
  warn "sbx login failed."
  note "Most likely: a mistyped username (it is the username, not the email),"
  note "an expired token, or a scope narrower than Read-only. Re-run this wizard."
  exit 1
fi

unset DOCKER_PAT

printf '\n'
say "Confirming the sign-in with a command that needs it:"
# `sbx diagnose`, NOT `sbx policy ls`. The obvious check is the wrong one: on a
# fresh box sbx checks policy initialization BEFORE authentication, so
# `sbx policy ls` fails with "global network policy has not been initialized"
# even after a perfectly good login - and stage 4 is where that gets fixed.
# Using it here would abort the wizard one stage before the thing it complains
# about gets set up. diagnose reports the two independently.
if on_loop 'sbx diagnose' 2>/dev/null |
     sed 's/\x1b\[[0-9;]*m//g' | grep -q 'Authentication.*authenticated'; then
  printf '  %s✓%s sbx diagnose reports authenticated\n' "$GREEN" "$RESET"
else
  warn "sbx login returned success, but diagnose does not report authenticated."
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx diagnose\"'"
  exit 1
fi
printf '\n'
pause "Press Enter to read the egress policy."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Egress - read the default posture, do not assume it"
say "Docker's own security page warns its defaults 'include broad wildcards'"
say "and names *.googleapis.com as one. It never publishes the list, so the only"
say "honest way to know what this boundary lets out is to ask this boundary."
printf '\n'
# This used to ask which profile to initialize, defaulting to `balanced`. It no
# longer offers the choice, because since #100 there is no choice to make here:
# the profile and its allowlist are declared in
# ansible/roles/loop_execution_boundary/defaults/main.yml and reconciled by the
# play. A wizard that also chose one would be a second place the posture is
# decided, and the two would disagree the first time either moved.
if ! on_loop 'sbx policy ls' >/dev/null 2>&1; then
  warn "no global network policy is initialized on this box yet."
  say "That is not a question for this walkthrough. The posture is declared -"
  say "'deny-all' plus an explicit allowlist - and the play is what applies it:"
  printf '\n'
  note "  cd /srv/orchestration/ansible && ansible-playbook loop.yml"
  printf '\n'
  say "Run that, then run this walkthrough again from the start."
  exit 1
fi

NOTES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../notes" 2>/dev/null && pwd || printf %s "${TMPDIR:-/tmp}")"
POSTURE_FILE="${POSTURE_FILE:-${NOTES_DIR}/loop-sbx-policy-$(date -u +%Y-%m-%d).txt}"
on_loop 'sbx policy ls --wide' | tee "$POSTURE_FILE"
printf '\n'
printf '  %s✓ saved%s %s\n' "$GREEN" "$RESET" "$POSTURE_FILE"
note "Commit it if this is a fresh box: the recorded posture is only as current"
note "as the sbx version and profile that printed it."
printf '\n'
warn "Read it before a Run: every domain above is somewhere an unattended agent"
warn "can send a repository. Widening it is a commit to the role's defaults, not"
warn "an 'sbx policy allow' typed on the box - the next apply would undo that."
printf '\n'
pause "Press Enter to boot a microVM and prove the boundary is real."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Proof - a command inside the microVM"
say "Signing in proves an identity, not a boundary. This boots an agent-less"
say "sandbox and asks the guest what kernel it is running, then compares."
note "First run pulls an image; give it a couple of minutes."
printf '\n'

PROOF_SANDBOX="sbx-login-proof-$$"
if ! on_loop "mkdir -p /home/loop/proof && sbx create --name ${PROOF_SANDBOX} shell /home/loop/proof"; then
  warn "could not create a sandbox. 'sbx diagnose' on the box is the next read."
  exit 1
fi

printf '\n'
# systemd-detect-virt is printed for both sides and is deliberately NOT the
# test: it answers `kvm` on the host, which is a DigitalOcean droplet, and
# `none` in the guest, which exposes no DMI for it to read. It reads backwards.
# The kernel release and the boot_id are the honest comparison.
say "host (uname -r, boot_id, systemd-detect-virt):"
on_loop 'uname -r; cat /proc/sys/kernel/random/boot_id; systemd-detect-virt || true' | sed 's/^/    /'
printf '\n'
say "inside the sandbox (the same three):"
on_loop "sbx exec ${PROOF_SANDBOX} sh -c 'uname -r; cat /proc/sys/kernel/random/boot_id; cat /sys/class/dmi/id/product_name 2>/dev/null || true'" | sed 's/^/    /'
printf '\n'
warn "A different kernel release and a different boot_id is the assertion: the"
warn "guest is not sharing this host's kernel. Same kernel would mean a"
warn "container, and the boundary would not be what ADR 0003 relies on."
note "Ignore systemd-detect-virt here - it reads backwards, kvm on the host and"
note "none in the guest, because the microVM exposes no DMI. It is printed only"
note "so nobody later mistakes it for the check."
printf '\n'

if confirm "Remove the proof sandbox now?"; then
  on_loop "sbx rm --force ${PROOF_SANDBOX} && rm -rf /home/loop/proof" || \
    warn "could not remove ${PROOF_SANDBOX} - clean it up with 'sbx rm'."
else
  SKIPPED+=("remove the proof sandbox: ssh root@${LOOP_HOST} 'su - loop -c \"sbx rm -f ${PROOF_SANDBOX}\"'")
fi

finish
