#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Log the Loop's agent in, and prove the credential works inside the boundary.
#
# This is the third and last of the spec's human-only steps, alongside the
# Docker sign-in (#78) and registering the signing key (#81). Claude Code's
# subscription login opens a browser and the box is headless -
# but unlike the other two there is no --password-stdin route, because what is
# being established is an OAuth session rather than a token you can paste.
#
# So this one is genuinely interactive: it hands you a terminal on the box, you
# run /login inside it, and your own browser completes the exchange. What is
# left behind is ~loop/.claude/.credentials.json, which is the model credential
# in the box's inventory and the thing `loop/agents/claude.sh` copies into each
# Iteration's microVM.
#
# Two things worth knowing before you start:
#
#   - The subscription is the credential, deliberately. A metered API key would
#     be simpler and is what `sbx secret set anthropic` wants, but spec #73's
#     user story 32 is written to make a metered key impossible to slip in: it
#     has no per-Run ceiling behind it, and the Termination Contract is the
#     whole cost control. `loop/agents/claude.sh` refuses to run an Iteration
#     with ANTHROPIC_API_KEY set, and `loop/assert-credentials.sh` refuses a box
#     that holds one anywhere.
#   - The credential goes INSIDE the microVM, where the agent can read it. That
#     is a stated cost rather than an oversight - ADR 0011 - and it is why the
#     egress allowlist (#100) and a subscription that revokes on its own are the
#     controls around it rather than the proxy injection `sbx` offers for API
#     keys.
#
# Run it from the orchestration VM as `conductor`, whose SSH key is the one
# attached to the droplet (`tofu/hosts/loop.tf`):
#
#   sudo -u conductor -i
#   cd /srv/orchestration/lab/single-user-factory/wizards && ./loop-claude-login.sh
#
# Re-runnable: logging in again over an existing session is harmless, and every
# check outside stage 2 is a read.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Required, and deliberately without a default (issue #3): the box's hostname
# is a fact about an instance, and a wizard that defaulted to somebody else's
# would walk an operator through minting a credential and then place it there.
LOOP_HOST="${LOOP_HOST:-}"
[[ -n ${LOOP_HOST} ]] || {
    printf 'LOOP_HOST is not set, and there is no default for it: where the box of this instance is, is a fact about this instance, not about Tracewake.\n' >&2
    exit 1
}
CREDENTIALS_PATH="/home/loop/.claude/.credentials.json"

# Nothing this wizard captures is persisted - the credential is established on
# the box and never travels through here. Pointed at /dev/null deliberately, so
# a stray write_env cannot drop anything into whatever directory this was run
# from.
ENV_FILE=/dev/null

# Every command runs on the box as `loop`, the unprivileged account a Run
# executes as - and therefore the account whose login state is the one that
# matters. Logging in as root would leave `loop` still logged out, and a Run
# would find out one microVM at a time.
on_loop() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

# The same, with a terminal. Stage 2 is the only thing in any of these wizards
# that needs one: Claude Code's /login is a full-screen interface, and without
# -t it renders as escape codes into a pipe and reads nothing back.
on_loop_tty() {
  ssh -t -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

banner "The Loop's agent - log in"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight - the box, the agent, the boundary"
say "Nothing here needs you yet. Checking what ansible already left on the box."
printf '\n'

if ! on_loop 'true' >/dev/null 2>&1; then
  warn "cannot reach loop as root@${LOOP_HOST} over SSH."
  note "The droplet's key is conductor's on the orchestration VM. If you are"
  note "someone else, re-run this as: sudo -u conductor -i"
  exit 1
fi
printf '  %s✓%s SSH to root@%s\n' "$GREEN" "$RESET" "$LOOP_HOST"

CLAUDE_VERSION=$(on_loop '/home/loop/.local/bin/claude --version' 2>/dev/null || true)
if [[ -z "$CLAUDE_VERSION" ]]; then
  warn "the agent is not installed, or not runnable as the loop account."
  note "Install it first:  cd /srv/orchestration/ansible && ansible-playbook loop.yml"
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$CLAUDE_VERSION"

# The collision spec #73 story 32 wants made impossible, checked before the
# login rather than after it. Claude Code prefers ANTHROPIC_API_KEY over a
# subscription session, so logging in on a box that holds one would produce a
# credential that is never used and a bill nobody expected - with no error and
# no difference in the output.
if on_loop 'test -n "${ANTHROPIC_API_KEY:-}"' 2>/dev/null; then
  warn "ANTHROPIC_API_KEY is set in the loop account's environment."
  note "It would supersede the login you are about to make and move every"
  note "Iteration onto metered billing. Find it and remove it first:"
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"grep -rl ANTHROPIC_API_KEY ~/.bashrc ~/.profile /etc/environment\"'"
  exit 1
fi
printf '  %s✓%s no metered model key in the Run account'"'"'s environment\n' "$GREEN" "$RESET"

if on_loop 'sbx daemon status' >/dev/null 2>&1; then
  printf '  %s✓%s the Execution Boundary is up\n' "$GREEN" "$RESET"
else
  warn "sandboxd is not running - stage 4 cannot prove anything without it."
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx daemon status; sbx diagnose\"'"
  exit 1
fi

if on_loop "test -f ${CREDENTIALS_PATH}"; then
  printf '\n'
  note "A model credential is already on the box. Logging in again replaces it,"
  note "which is harmless; stages 3 to 5 re-check it either way."
fi

printf '\n'
pause "Press Enter to log in."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The box - log in as yourself"
say "This is the step only you can take. A terminal on the box opens below,"
say "running the agent. Your subscription is what it will be billed against, so"
say "log in as the account that holds it."
printf '\n'
step "At the prompt, type:  /login"
step "Choose your subscription account, not an API key."
step "It prints a URL. Open it on your own machine and approve."
step "Paste the code it gives you back into the terminal."
step "Then type:  /exit"
printf '\n'
warn "You are on ${LOOP_HOST}, not this VM. Nothing else lives there,"
warn "but it is the box an unattended agent runs on - do not ask it to do work."
printf '\n'
pause "Press Enter to open the terminal on the box."

on_loop_tty '/home/loop/.local/bin/claude' || true

printf '\n'

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The credential - on the box, and only readable by the box"
say "Checking what the login actually left behind, rather than trusting that it"
say "finished."
printf '\n'

if ! on_loop "test -f ${CREDENTIALS_PATH}"; then
  warn "no credential at ${CREDENTIALS_PATH}."
  note "The login did not complete. Re-run this wizard; stage 2 is repeatable."
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$CREDENTIALS_PATH"

CRED_MODE=$(on_loop "stat -c %a ${CREDENTIALS_PATH}" 2>/dev/null || printf '?')
if [[ "$CRED_MODE" == "600" ]]; then
  printf '  %s✓%s mode 0600 - readable by loop and nobody else\n' "$GREEN" "$RESET"
else
  warn "mode is ${CRED_MODE}, not 600. Tightening it."
  on_loop "chmod 0600 ${CREDENTIALS_PATH}" || warn "could not chmod it - do it by hand."
fi

say "Asking the agent to answer one question, on the box, to prove the session"
say "is live rather than merely present:"
printf '\n'
if on_loop '/home/loop/.local/bin/claude --print --max-turns 1 "Reply with the single word: ready"' 2>&1 |
     sed 's/^/    /' | grep -qi 'ready'; then
  printf '\n  %s✓%s the agent answered\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "the agent did not answer. The credential is there and the session may"
  warn "not be. Re-run stage 2."
  exit 1
fi

printf '\n'
pause "Press Enter to prove it works inside the boundary."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The boundary - the same credential, inside a microVM"
say "The stage above proved the login works on the host. A Run never runs the"
say "agent there: every Iteration is a fresh microVM, and the credential is"
say "copied in and dies with it. That is a different claim, so it is proved"
say "separately - through the exact adapter a Run uses."
note "First run pulls the agent's sandbox image; give it a couple of minutes."
printf '\n'

PROOF_PROMPT="/tmp/loop-claude-login-proof-$$"
if on_loop "mkdir -p /home/loop/proof && printf 'Reply with the single word: ready\n' > ${PROOF_PROMPT} && cd /home/loop/proof && /home/loop/loop/agents/claude.sh ${PROOF_PROMPT} 1; rm -f ${PROOF_PROMPT}" 2>&1 |
     sed 's/^/    /' | grep -qi 'ready'; then
  printf '\n  %s✓%s the agent answered from inside a microVM\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "the agent did not answer from inside the boundary."
  note "The credential is fine on the host, so this is the boundary or the"
  note "adapter. Read it on the box:"
  note "  ssh root@${LOOP_HOST} 'su - loop -c \"sbx diagnose; sbx policy ls --wide\"'"
  note "If it is egress, the fix is a line in loop_execution_boundary_egress_common"
  note "saying what breaks without it - not widening the profile."
  SKIPPED+=("prove the credential works inside the boundary")
fi

on_loop 'rm -rf /home/loop/proof' || true

printf '\n'
pause "Press Enter for the credential inventory."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The inventory - four credentials, and nothing else"
say "Every isolation argument in spec #73 rests on one sentence about what this"
say "box holds. This is that sentence, asserted - and the model credential's"
say "line now gates it, which it did not until this wizard was run."
printf '\n'

if on_loop '/home/loop/loop/assert-credentials.sh' 2>&1 | sed 's/^/    /'; then
  printf '\n  %s✓%s the box holds what it is allowed to hold, and nothing it is not\n' \
    "$GREEN" "$RESET"
else
  printf '\n'
  warn "the inventory is not clean. Every violation is named above."
  note "It never fixes what it finds: what to do about a credential that reached"
  note "this box is not a decision to take unattended."
  SKIPPED+=("clear the credential violations named above")
fi

printf '\n'
say "The box is ready for a Run. Seeding one is the next command, and it runs"
say "here rather than there - fetching the task is the operator's, not the"
say "Loop's (ADR 0010)."
printf '\n'
note "  cd /srv/orchestration/lab/single-user-factory/loop"
note "  ./seed-run.sh --repo <checkout> --task 648 --area 'dashboards and reports' \\"
note "      --check \"...\""

finish
