#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# The Loop's GitHub credentials, and the proof that they produce a Verified
# commit attributed to the operator.
#
# `ansible-playbook loop.yml` (role `loop_credentials`) has already generated a
# dedicated SSH signing key ON the box and configured git to sign every commit
# with it. Two things remain, and neither can be done by a machine:
#
#   1. Registering that public key to the operator's GitHub account AS A SIGNING
#      KEY. That is a different registration from an authentication key - the
#      same key pasted into the wrong box authenticates and does not verify - and
#      it happens in a browser signed in as the operator.
#   2. Creating a fine-grained personal access token scoped to one repository.
#      GitHub has no API that mints one; it is a browser form.
#
# The third stage is the one that matters: it makes a commit on the box, pushes
# it to a throwaway branch, and reads back from GitHub whether it arrived
# attributed and Verified. Until that has happened, the first two stages are two
# things that look right.
#
# What "Verified" means here is deliberate and not the conventional reading. ADR
# 0005: a Verified Loop commit asserts that the operator CAUSED it - he chose the
# task, set the Termination Contract and owns the result - not that he typed it.
# The key's distinct title is what keeps the two distinguishable, which is why
# this wizard tells you the title to use rather than leaving it to taste.
#
# Run it from the orchestration VM as `conductor`, whose SSH key is the one
# attached to the droplet (`tofu/hosts/loop.tf`):
#
#   sudo -u conductor -i
#   cd /srv/orchestration/lab/single-user-factory/wizards
#   ./loop-github-credentials.sh
#
# Re-runnable. Every check is a read, the token is replaced rather than
# appended, and a key already registered is left alone.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Required, and deliberately without a default (issue #3): a hostname or a
# repository is a fact about an instance, and a wizard that defaulted to
# somebody else's would walk an operator through minting a token and then
# push it there.
#
# One helper rather than a check per variable, because the message is the
# useful part - it says what the value IS, which is what tells an operator
# which line to write.
need_env() {
    local name="$1" what="$2"
    if [[ -z ${!name:-} ]]; then
        printf '%s is not set, and there is no default for it: %s is a fact about this instance, not about Tracewake.\n' \
            "${name}" "${what}" >&2
        exit 1
    fi
    printf '%s' "${!name}"
}

LOOP_HOST="$(need_env LOOP_HOST "where the box of this instance is")"
# Read here rather than where it is used, four hundred lines down. Both are
# required, and finding out about the second one after the operator has minted
# a token in a browser is a walkthrough that wastes the one thing it exists to
# spend carefully.
NEGATIVE_PROBE_REPO="$(need_env LOOP_TOKEN_NEGATIVE_PROBE_REPO \
    "a repository this token must NOT be able to see - the probe that proves the scope stops at one repository")"

# Nothing this wizard captures is persisted on this side, so there is no .env to
# upsert into. Pointed at /dev/null deliberately rather than left at the library
# default, so a stray `write_env` cannot drop a GitHub token into whatever
# directory this was run from.
ENV_FILE=/dev/null

wizard_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# Where the values below are declared. The role's defaults carry the ones that
# are the product's (the credentials directory, the key path); the ones that
# name a person, a host or a repository are the instance's and live in its own
# inventory, which is what TRACEWAKE_INSTANCE_VARS points at (issue #3).
# `examples/inventory.yml` is the shape of that file.
role_defaults="${wizard_dir}/../deploy/ansible/roles/loop_credentials/defaults/main.yml"
instance_vars="${TRACEWAKE_INSTANCE_VARS:-}"
assert_script="${wizard_dir}/../loop/assert-credentials.sh"

# The key title, the target repository, the author email and the account they
# must resolve to are declared in the role's defaults and read from there. A
# walkthrough carrying its own copy would be a second place they are decided,
# and the two would disagree the first time either moved - the same reason stage
# 4 of the sbx walkthrough stopped offering an egress profile.
#
# There is deliberately no fallback value. A default that quietly stood in for
# an unreadable file is exactly the second copy this avoids, and it would be
# discovered by a token minted for the wrong repository.
role_default() {
    local key="$1" value="" file=""
    for file in "${instance_vars}" "${role_defaults}"; do
        [[ -n ${file} && -f ${file} ]] || continue
        value="$(sed -nE "s/^${key}:[[:space:]]*(.*[^[:space:]])[[:space:]]*$/\1/p" \
            "${file}" | head -n1)"
        [[ -n ${value} ]] || continue
        printf '%s' "${value}"
        return 0
    done
    warn "no ${key} is declared in ${instance_vars:-<TRACEWAKE_INSTANCE_VARS unset>} or ${role_defaults}"
    note "It names a person, a host or a repository, so it is an instance value:"
    note "declare it in your inventory and point TRACEWAKE_INSTANCE_VARS at it."
    exit 1
}

SIGNING_KEY_TITLE="$(role_default loop_signing_key_title)"
TARGET_REPO="$(role_default loop_target_repository)"
AUTHOR_EMAIL="$(role_default loop_commit_author_email)"
GITHUB_ACCOUNT="$(role_default loop_github_account)"
TOKEN_FILE="$(role_default loop_credentials_dir)/github-token"

# Every command runs on the box, as `loop` - the account a Run executes as, and
# therefore the account whose credentials are the ones that matter. The same
# shape the sbx walkthrough uses.
# -n: ssh reads this wizard's stdin unless told not to, so an on_loop inside a
# `while read` loop would swallow the loop's input. The flag is the whole
# difference between these two functions, and a helper that sometimes consumes
# the caller's stdin is a trap.
on_loop() {
    ssh -n -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
        "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

# The same, for the two calls that feed the box on stdin - the token, and the
# credential assertion piped in as a script.
on_loop_stdin() {
    ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
        "su - loop -s /bin/bash -c $(printf '%q' "$1")"
}

# The token never comes back to this machine. Every call that needs it reads it
# from the file on the box, inside the same shell that uses it.
on_loop_with_token() {
    on_loop "token=\$(cat ${TOKEN_FILE}); $1"
}

banner "The Loop's GitHub credentials - and one Verified commit"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight - what ansible has already left on the box"
say "Nothing here needs you yet. The signing key is generated by the play, not"
say "by you and not by this wizard: ADR 0005 says it is generated ON the box and"
say "never moved, so the operator's laptop key stays on the laptop."
printf '\n'

if ! on_loop 'true' >/dev/null 2>&1; then
    warn "cannot reach loop as root@${LOOP_HOST} over SSH."
    note "The droplet's key is conductor's on the orchestration VM. If you are"
    note "someone else, re-run this as: sudo -u conductor -i"
    exit 1
fi
printf '  %s✓%s SSH to root@%s\n' "$GREEN" "$RESET" "$LOOP_HOST"

if ! on_loop 'test -f ~/.ssh/loop_signing_ed25519.pub'; then
    warn "no signing key on the box."
    note "Generate it with the play, not by hand:"
    note "  cd /srv/orchestration/ansible && ansible-playbook loop.yml"
    exit 1
fi
printf '  %s✓%s signing key present\n' "$GREEN" "$RESET"
on_loop 'ssh-keygen -lf ~/.ssh/loop_signing_ed25519.pub' | sed 's/^/    /'

for setting in gpg.format:ssh commit.gpgsign:true; do
    want="${setting#*:}"
    got="$(on_loop "git config --global --get ${setting%%:*}" | tr -d '\r')"
    if [[ ${got} != "${want}" ]]; then
        warn "git ${setting%%:*} on the box is '${got}', expected '${want}'."
        note "  cd /srv/orchestration/ansible && ansible-playbook loop.yml"
        exit 1
    fi
done
printf '  %s✓%s git signs every commit, with the ssh format\n' "$GREEN" "$RESET"
printf '\n'
pause "Press Enter to register the key with GitHub."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub - register the key as a SIGNING key"
say "This is the first step only you can take. The key below is public - it is"
say "safe on a screen, in a screenshot, and in this terminal's scrollback."
printf '\n'
PUBKEY="$(on_loop 'cat ~/.ssh/loop_signing_ed25519.pub' | tr -d '\r')"
printf '%s%s%s\n' "$DIM" "${PUBKEY}" "$RESET"
printf '\n'
open_url "https://github.com/settings/ssh/new"
step "If that did not open: github.com → Settings → SSH and GPG keys → New SSH key."
step "Title: ${SIGNING_KEY_TITLE}"
step "Key type: **Signing Key**. Not 'Authentication Key' - that is the trap."
step "  The same key in the wrong box lets the box log in and leaves every"
step "  commit Unverified, with no error anywhere to say why."
step "Key: paste the line above, whole."
step "Add SSH key."
printf '\n'
note "Why a title at all: ADR 0005 makes the KEY the thing that distinguishes a"
note "Loop commit from one you hand-wrote, because ETA policy forbids an"
note "AI-attribution trailer in a commit message. Which key signed a commit is"
note "visible; the title is what makes that readable."
printf '\n'
warn "If you are re-running this and the key is already registered, GitHub will"
warn "say 'key is already in use'. That is a pass, not a failure - skip to the"
warn "next stage."
printf '\n'
pause "Registered? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GitHub - create the repository-scoped token"
say "The second step only you can take: GitHub has no API that mints a"
say "fine-grained token, so this is a browser form or it is nothing."
printf '\n'
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: ${LOOP_HOST}"
step "Resource owner: ${TARGET_REPO%%/*}"
step "Expiration: your call. When it lapses a Run fails at its push, loudly,"
step "  with everything it did still on the box."
step "Repository access: 'Only select repositories' → ${TARGET_REPO}"
step "  ONE repository. This is the property the whole isolation argument rests"
step "  on: spec #73's blast radius stops at one repository, and it stops there"
step "  because of what you select on this screen."
step "Permissions → Repository permissions:"
step "  Contents: Read and write        (the branch a Run pushes)"
step "  Pull requests: Read and write   (the draft PR a Run opens)"
step "  Issues: leave at No access      (ADR 0010 - a Run does not read issues;"
step "                                   the operator seeds the Run off the box)"
step "  Metadata: Read-only             (GitHub adds this itself)"
step "  Nothing else. Not Actions, not Administration, not Secrets."
step "Generate token, then copy it. GitHub shows it exactly once."
printf '\n'
note "It is an organisation-owned repository, so the token may sit in"
note "'pending' until an owner approves it. You are an owner."
printf '\n'
ask_secret GITHUB_TOKEN "Paste the token:"

if [[ -z ${GITHUB_TOKEN} ]]; then
    warn "No token. Re-run when you have one."
    exit 1
fi
if [[ ${GITHUB_TOKEN} != github_pat_* ]]; then
    warn "That does not look like a fine-grained token (they start github_pat_)."
    warn "A classic token cannot be scoped to one repository, and the box's own"
    warn "credential assertion rejects one."
    confirm "Send it anyway?" || exit 1
fi

# A redirect, not `install -D -m 600 /dev/stdin`, which is the obvious way and
# does not work: under `su - loop` that path is the ssh pipe, still owned by
# root, and loop cannot open it - `install: cannot open '/dev/stdin'`. `cat`
# with no argument reads the descriptor it was handed rather than opening
# anything, so it does not care who owns it.
#
# umask 077 then mv, rather than write-then-chmod: the temporary file is 0600
# from its first byte and `mv` carries that mode onto the destination, so the
# token is never on disk in a mode anyone else could read - not even for the
# instant a chmod would take, and not at all on a re-run over a file that was
# already there with a wider mode.
if printf '%s\n' "${GITHUB_TOKEN}" |
    on_loop_stdin "umask 077 && mkdir -p $(dirname "${TOKEN_FILE}") && cat > ${TOKEN_FILE}.new && mv ${TOKEN_FILE}.new ${TOKEN_FILE}"; then
    printf '  %s✓%s token written to %s on the box, mode 0600\n' "$GREEN" "$RESET" "${TOKEN_FILE}"
else
    warn "could not write the token to the box."
    exit 1
fi
unset GITHUB_TOKEN

printf '\n'
say "Where it is NOT: neither shared secret manifest. The token belongs to the"
say "box (spec #73), so no vaulted-agent session and no legacy wrapper has it."
for manifest in /etc/vaulted-agent/manifests/orchestrator-all.env.tpl /srv/orchestration/env.tpl; do
    if [[ ! -r ${manifest} ]]; then
        note "  ? ${manifest} not readable from here - check it by hand"
    elif grep -qi 'loop' "${manifest}"; then
        warn "  ${manifest} mentions 'loop' - read it: the token must not be there"
    else
        printf '  %s✓%s %s holds no Loop reference\n' "$GREEN" "$RESET" "${manifest}"
    fi
done
printf '\n'
pause "Press Enter to check what the token can reach."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The token - what it can reach, and what it cannot"
say "A token scoped to one repository is a claim until something asks GitHub."
printf '\n'

api_status() {
    on_loop_with_token "curl -sS -o /dev/null -w '%{http_code}' \
        -H \"Authorization: Bearer \$token\" \
        -H 'Accept: application/vnd.github+json' \
        https://api.github.com/$1" | tr -d '\r'
}

code="$(api_status "repos/${TARGET_REPO}")"
if [[ ${code} == "200" ]]; then
    printf '  %s✓%s %s  reachable (%s)\n' "$GREEN" "$RESET" "${TARGET_REPO}" "${code}"
else
    warn "${TARGET_REPO} answered ${code}, not 200."
    note "401: the token is wrong or expired. 404: it is not scoped to this"
    note "repository, or an organisation owner has not approved it yet."
    exit 1
fi

# The negative probe is the one that matters. A token that can see a second
# repository is wider than the acceptance criterion, and nothing later in this
# wizard would notice.
# Any repository the token must NOT see. Which one is the instance's to say -
# "a repository this operator owns and this token is not for" has no
# product-wide answer - but THAT there is one is not optional. Required rather
# than skippable, because this is the probe that actually enforces ADR 0009's
# blast radius, and a check that quietly does not run is worse than one that
# was never written: the walkthrough would still print a tick beside the
# positive probe and the operator would read the pair as "the scope holds".
other="${NEGATIVE_PROBE_REPO}"
code="$(api_status "repos/${other}")"
if [[ ${code} == "404" ]]; then
    printf '  %s✓%s %s  invisible (404) - the scope holds\n' \
        "$GREEN" "$RESET" "${other}"
else
    printf '\n'
    warn "${other} answered ${code}. The token can see a repository it should not."
    warn "Spec #73's blast radius is 'one repository'; this token is wider."
    note "Narrow it at github.com/settings/personal-access-tokens and re-run."
    confirm "Continue anyway with a wider token?" || exit 1
fi

note "Not probed, and it should be: whether the token can read issues. ADR 0010"
note "makes 'a Run cannot fetch a task' a property of this token holding no Issues"
note "permission, which is why stage 3 says to leave it at No access - but there"
note "is no call that separates the two cases. GitHub's list-issues endpoint is"
note "satisfied by Pull requests: read, which this token must hold, so a 200 there"
note "proves nothing; and GitHub publishes no endpoint reporting a fine-grained"
note "token's own permission set. Leaving the permission unset is the control."
printf '\n'

note "Not probed, on purpose: whether the token can push to the default branch."
note "Branch protection on ${TARGET_REPO} requires a review, and an unattended"
note "Run that tried would be a Run testing a backstop rather than using it."
printf '\n'
pause "Press Enter to make the commit that proves all of this."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Proof - one commit, attributed and Verified"
say "The box makes a commit, signs it with the key you registered, pushes it to"
say "a throwaway branch, and GitHub is asked what it thinks of it."
printf '\n'
note "It is an orphan branch built in a fresh repository, not a clone of"
note "${TARGET_REPO} - that repository is about a gigabyte, and cloning it to"
note "make one commit would cost minutes to prove nothing extra. What is being"
note "proved is the box's identity, its key and its token, and a single commit"
note "exercises all three."
printf '\n'

BRANCH="loop/verified-proof-$(date -u +%Y%m%d-%H%M%S)"
PROOF_DIR="/home/loop/verified-proof"

if ! on_loop "$(
    cat <<PROOF
set -e
rm -rf ${PROOF_DIR}
mkdir -p ${PROOF_DIR}
cd ${PROOF_DIR}
git init -q -b ${BRANCH}
printf 'Throwaway. Proof that a commit made on the box arrives attributed and\nVerified. Delete this branch.\n' > LOOP-VERIFIED-PROOF.md
git add LOOP-VERIFIED-PROOF.md
git commit -q -m 'Loop: prove a Verified commit on a throwaway branch'
git log -1 --format='%H %an <%ae> %G? %GK'
PROOF
)"; then
    warn "the commit failed on the box."
    note "  ssh root@${LOOP_HOST} 'su - loop -c \"cd ${PROOF_DIR} && git log\"'"
    exit 1
fi

printf '\n'
say "The box's own verdict on its own signature (git verify-commit):"
if on_loop "cd ${PROOF_DIR} && git verify-commit HEAD" 2>&1 | sed 's/^/    /'; then
    printf '  %s✓%s the box can verify its own signature\n' "$GREEN" "$RESET"
else
    warn "the box cannot verify its own signature."
    note "That is the allowed_signers file, not GitHub. Re-run the play."
    exit 1
fi

printf '\n'
say "Pushing ${BRANCH} to ${TARGET_REPO}..."
if ! on_loop "cd ${PROOF_DIR} && git remote add origin https://github.com/${TARGET_REPO}.git && git push -q origin ${BRANCH}"; then
    warn "the push failed."
    note "The token needs Contents: Read and write. Re-run from stage 3."
    exit 1
fi
printf '  %s✓%s pushed\n' "$GREEN" "$RESET"

SHA="$(on_loop "cd ${PROOF_DIR} && git rev-parse HEAD" | tr -d '\r')"
printf '\n'
say "What GitHub says about ${SHA:0:12}:"
# jq, on the box, where `loop_base` installs it. Reaching for sed here would
# mean taking whichever "login" appeared first in the payload - the commit's
# author object, the committer's, or the verifier's - and they are not the same
# field. The one that answers "attributed to whom" is .author.login.
VERDICT="$(on_loop_with_token "curl -sS -H \"Authorization: Bearer \$token\" \
    -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/${TARGET_REPO}/commits/${SHA} |
    jq -r '[.author.login // \"\", .commit.verification.verified, .commit.verification.reason] | @tsv'")"

IFS=$'\t' read -r login verified reason <<<"${VERDICT}"

printf '    author account : %s  (expected %s)\n' "${login:-<none>}" "${GITHUB_ACCOUNT}"
printf '    author email   : %s\n' "${AUTHOR_EMAIL}"
printf '    verified       : %s (%s)\n' "${verified:-?}" "${reason:-?}"
printf '\n'

# Compared to the operator's account, not merely non-empty. The criterion is
# "attributed to the operator"; a commit attributed to somebody else would
# satisfy a non-empty check and fail the ticket.
PROOF_OK=false
if [[ ${verified} == "true" && ${login} == "${GITHUB_ACCOUNT}" ]]; then
    PROOF_OK=true
    printf '  %s✓ attributed to %s and Verified%s\n' "$GREEN" "${login}" "$RESET"
    note "Read as ADR 0005 defines it: the operator CAUSED this commit."
else
    warn "not verified, or not attributed to ${GITHUB_ACCOUNT}."
    note "verified=false, reason=unsigned      the key never signed - check the play."
    note "verified=false, reason=unknown_key   the key is registered as an"
    note "  AUTHENTICATION key, not a signing key. That is stage 2's trap; add it"
    note "  again at github.com/settings/ssh/new with Key type: Signing Key."
    note "no author account                    ${AUTHOR_EMAIL} is not a verified"
    note "  email on the GitHub account. Add it at github.com/settings/emails."
fi
printf '\n'
say "Look at it yourself:"
note "  https://github.com/${TARGET_REPO}/commits/${BRANCH}"
printf '\n'

if confirm "Delete the throwaway branch and the proof directory now?"; then
    if on_loop "cd ${PROOF_DIR} && git push -q origin --delete ${BRANCH} && cd / && rm -rf ${PROOF_DIR}"; then
        printf '  %s✓%s branch and directory gone\n' "$GREEN" "$RESET"
    else
        SKIPPED+=("delete ${BRANCH} on ${TARGET_REPO} - the push -q --delete failed")
    fi
else
    SKIPPED+=("delete ${BRANCH} on ${TARGET_REPO}, and ${PROOF_DIR} on the box")
fi

${PROOF_OK} || exit 1

printf '\n'
pause "Press Enter for the credential inventory."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The inventory - what the box holds, and what it does not"
say "The box's own assertion, run on the box, as the account a Run executes as."
say "It is piped over SSH rather than installed: nothing in the play puts the"
say "Loop's scripts on the box yet (#83), and a walkthrough should not be the"
say "thing that first does."
printf '\n'

if [[ ! -f ${assert_script} ]]; then
    warn "cannot find ${assert_script}"
    exit 1
fi

if on_loop_stdin 'bash -s -- --home /home/loop' <"${assert_script}"; then
    printf '\n  %s✓ clean%s\n' "$GREEN" "$RESET"
else
    printf '\n'
    warn "the box reports violations - read them above."
    SKIPPED+=("resolve the credential violations the box reported")
fi

printf '\n'
pause "Press Enter for the half that run could not see."

# The complement. /root is mode 0700, so the run above reports `[partial]` for
# every family with a probe under it - it could not look, which is not the same
# answer as looking and finding nothing. This run can look there and cannot see
# the environment a Run actually gets. Neither run alone covers the fifth
# acceptance criterion; the pair does.
say "The same script as root, for the paths root owns. It will report"
say "docker-identity as unknown - root has no sbx session, and that is correct:"
say "the account whose boundary matters is the one a Run executes as."
printf '\n'
ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${LOOP_HOST}" \
    'bash -s -- --home /home/loop' <"${assert_script}" |
    sed -n '/^Forbidden/,/^$/p;/^Could not/,/^$/p' || true

printf '\n'
note "Four credentials, not three. Spec #73 says three; sbx will not create a"
note "sandbox without a Docker identity, so the Execution Boundary itself"
note "requires a fourth (#78). It is a read-only Docker PAT: it reads Docker Hub,"
note "it revokes on its own, and revoking it stops the boundary rather than"
note "degrading it."

printf '\n'
pause "Press Enter for the last stage - how a finished Run reaches you."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "So a finished Run reaches you"
say "A Run started with --notify comments on the draft pull request it opened,"
say "which is the only surface the box can reach without a new host on the"
say "egress allowlist and a fifth credential (ADR 0013). That comment is the"
say "on-PR record; the email that tells you about it comes from the Selector"
say "on the orchestration VM (ADR 0018, amended 2026-08-31)."
printf '\n'
say "Do NOT turn on GitHub's 'your own updates' email setting for this. It was"
say "this stage's instruction once, and it flooded: the setting is"
say "account-global, every agent session acts as you, so it delivered all of"
say "their activity everywhere - not just the Loop's proposals. It is"
say "deliberately off (ADR 0013, amended)."
printf '\n'
step "Nothing to click here. Confirm the Selector's notifier is deployed"
step "  - until it is, a finished Run is visible on this instance's window"
step "  and on the proposal itself, but no email arrives."
printf '\n'

if ! confirm "Is the Selector's email notifier live?"; then
    SKIPPED+=("the Selector email notifier - until it ships, watch this instance's window; no email announces a finished Run")
fi

finish
